/** Field Journal Quest collection — guardians are field-guide seals and a child can actively choose a compact battle team. */
import { Link } from "wouter";
import { Check, Lock, Map, Shield, Sparkles, Trophy, UsersRound } from "lucide-react";
import GuardianSeal from "@/components/GuardianSeal";
import { GUARDIANS, STATIONS } from "@/game/gameData";
import { useGame } from "@/contexts/GameContext";

export default function CollectionPage() {
  const { profile, isStationMastered, isBossUnlocked, toggleTeamGuardian } = useGame();
  if (!profile) return <section className="evidence-card border-2 border-[#172a48] bg-[#fffdf6] p-6 shadow-[5px_5px_0_#172a48]"><h1 className="font-display text-4xl font-black">Bộ sưu tập cần hồ sơ riêng</h1><p className="mt-2 text-sm text-[#58708b]">Tạo sổ hành trình để thu phục guardian và chọn đội battle.</p><Link href="/start" className="mt-5 inline-flex border-2 border-[#172a48] bg-[#f6b73c] px-4 py-2.5 font-bold shadow-[2px_2px_0_#172a48]">Tạo hồ sơ</Link></section>;
  const completedStations = STATIONS.filter((station) => isStationMastered(station.id)).length;
  const verifiedStations = STATIONS.filter((station) => station.status === "ready").length;
  const stickerCount = Math.min(6, Math.floor(profile.correctQuestionIds.length / 5) + profile.metrics.bossWins);
  return <section><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="section-kicker">Sổ dấu ấn · đội battle</p><h1 className="font-display text-4xl font-black tracking-tight">Bộ sưu tập guardian</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-[#58708b]">Guardian chỉ gia nhập khi em có 10 câu đúng riêng biệt. Chọn tối đa ba guardian đã thu phục để mang vào trận Atlas.</p></div><span className="field-tag"><UsersRound size={14} /> {profile.teamGuardianIds.length}/3 trong đội</span></div>
    <section className="mb-6 border-2 border-[#172a48] bg-[#172a48] p-5 text-white shadow-[5px_5px_0_#f6b73c]"><div className="flex flex-wrap items-center justify-between gap-5"><div><p className="section-kicker text-[#f6b73c]">Đội đã niêm phong</p><h2 className="mt-1 font-display text-3xl font-black">{profile.teamGuardianIds.length ? "Sẵn sàng dùng ma thuật" : "Chọn một guardian đầu tiên"}</h2></div><div className="flex min-h-16 flex-wrap items-center gap-3">{profile.teamGuardianIds.length ? profile.teamGuardianIds.map((guardianId) => { const guardian = GUARDIANS.find((item) => item.id === guardianId); return guardian ? <div key={guardianId} className="flex items-center gap-2 border border-white/40 bg-white/10 p-2"><img src={guardian.sprite} alt={guardian.name} className="h-11 w-11 object-contain" /><span><b className="block">{guardian.name}</b><span className="text-xs text-[#d5dfed]">{guardian.element}</span></span></div> : null; }) : <p className="text-sm text-[#d5dfed]">Thu phục guardian ở một trạm đã kiểm chứng trước.</p>}</div></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{GUARDIANS.map((guardian) => { const unlocked = profile.collectedGuardianIds.includes(guardian.id); const inTeam = profile.teamGuardianIds.includes(guardian.id); const associatedStation = guardian.stationId === "boss" ? null : STATIONS.find((station) => station.id === guardian.stationId); const canBattle = unlocked && guardian.id !== "atlas"; return <article key={guardian.id} className={`evidence-card relative overflow-hidden border-2 border-[#172a48] bg-[#fffdf6] p-4 shadow-[4px_4px_0_#172a48] ${unlocked ? "" : "opacity-75"}`}><div className={`absolute right-0 top-0 h-14 w-14 border-b-2 border-l-2 border-[#172a48] ${unlocked ? guardian.tone : "bg-[#d7d0bf]"}`} /><div className="flex gap-4"><GuardianSeal guardian={guardian} unlocked={unlocked} compact progressLabel={unlocked ? "dấu ấn đã ghi" : "mẫu vật niêm phong"} /><div className="min-w-0"><p className="font-mono text-[10px] font-bold tracking-[0.14em] text-[#58708b]">FIELD SPECIMEN · {unlocked ? guardian.element.toUpperCase() : "?"}</p><h2 className="font-display text-3xl font-black">{unlocked ? guardian.name : "Mẫu vật ???"}</h2><p className="mt-1 text-xs leading-relaxed text-[#58708b]">{unlocked ? guardian.description : guardian.stationId === "boss" ? "Thắng Atlas để phá niêm phong cuối." : `Hoàn thành ${associatedStation?.title.toLowerCase()} để phá niêm phong.`}</p></div></div><div className="mt-4 flex items-center justify-between gap-3 border-t-2 border-dashed border-[#d7d0bf] pt-3 text-xs font-bold">{unlocked ? <span className="inline-flex items-center gap-1 text-[#235b45]"><Check size={14} /> {inTeam ? "Trong đội" : "Đã thu phục"}</span> : <span className="inline-flex items-center gap-1 text-[#58708b]"><Lock size={13} /> Đang niêm phong</span>}{canBattle ? <button onClick={() => toggleTeamGuardian(guardian.id)} className={`border-2 border-[#172a48] px-2 py-1 shadow-[1px_1px_0_#172a48] ${inTeam ? "bg-[#f6b73c]" : "bg-white"}`}>{inTeam ? "Bỏ khỏi đội" : "Chọn battle"}</button> : associatedStation ? <Link href={`/station/${associatedStation.id}`} className="underline decoration-2 underline-offset-4">Xem trạm</Link> : <Link href="/boss" className="underline decoration-2 underline-offset-4">{isBossUnlocked ? "Đến Boss" : "Điều kiện"}</Link>}</div></article>; })}</div>
    <section className="mt-8 overflow-hidden border-2 border-[#172a48] bg-[#fff8da] p-5 shadow-[5px_5px_0_#172a48]"><div className="grid gap-4 sm:grid-cols-[1fr_auto]"><div><p className="section-kicker">Sticker bằng chứng</p><h2 className="mt-1 font-display text-3xl font-black">{stickerCount}/6 dấu đóng trong nhật ký</h2><p className="mt-2 max-w-xl text-sm leading-relaxed text-[#58708b]">Cứ năm câu đúng riêng biệt nhận một sticker. Chiến thắng Atlas thêm một dấu đặc biệt.</p></div><div className="flex items-center gap-2 self-center">{Array.from({ length: 6 }, (_, index) => <span key={index} className={`grid h-10 w-10 place-items-center rounded-full border-2 border-[#172a48] ${index < stickerCount ? "bg-[#f6b73c]" : "bg-white/60 text-[#58708b]"}`}>{index < stickerCount ? <Sparkles size={17} /> : <Lock size={14} />}</span>)}</div></div></section><div className="mt-6 flex flex-wrap items-center gap-3 border-2 border-dashed border-[#172a48] bg-[#fffdf6] p-4"><Trophy size={18} /><span className="text-sm"><b>{completedStations}/20</b> station đã làm chủ; hiện có <b>{verifiedStations}</b> trạm đủ ngân hàng 10 câu kiểm chứng để mở.</span><Link href="/map" className="ml-auto text-sm font-bold underline decoration-2 underline-offset-4"><Map className="mr-1 inline" size={14} /> Trở lại bản đồ</Link></div></section>;
}
