/** Math4Fun home — Field Journal Quest presents a physical journal cover and the next field mission rather than a generic dashboard. */
import { Link } from "wouter";
import { ArrowRight, BookOpen, Compass, Crown, Flame, Gem, Map, ShieldCheck, Sparkles, Swords, Trophy } from "lucide-react";
import GuardianSeal from "@/components/GuardianSeal";
import { ARENA_IMAGE, HERO_IMAGE, STICKERS_IMAGE, getGuardian, STATIONS } from "@/game/gameData";
import { useGame } from "@/contexts/GameContext";

export default function Home() {
  const { progress, level, isStationUnlocked, isStationMastered, stationProgress, isBossUnlocked } = useGame();
  const nextStation = STATIONS.find((station) => isStationUnlocked(station.id) && !isStationMastered(station.id)) ?? STATIONS[STATIONS.length - 1];
  const guardian = getGuardian(nextStation.guardianId);
  const completedStations = STATIONS.filter((station) => isStationMastered(station.id)).length;
  const { done, total } = stationProgress(nextStation.id);

  return <section>
    <section className="relative overflow-hidden border-2 border-[#172a48] bg-[#172a48] shadow-[7px_7px_0_#f6b73c]"><img src={HERO_IMAGE} alt="Guardian Math4Fun thám hiểm tuyến số học" className="absolute inset-0 h-full w-full object-cover opacity-75" /><div className="absolute inset-0 bg-gradient-to-r from-[#172a48] via-[#172a48]/80 to-[#172a48]/10" /><div className="relative max-w-[720px] px-6 py-8 sm:px-9 sm:py-11"><span className="field-tag border-white/40 bg-white/10 text-white"><Compass size={13} className="text-[#f6b73c]" /> World 01 · Số & Quy luật</span><h1 className="mt-4 font-display text-4xl font-black leading-[0.92] tracking-tight text-white sm:text-5xl">Hôm nay, bạn sẽ tìm ra <em className="text-[#f6b73c]">quy luật</em> nào?</h1><p className="mt-4 max-w-md text-sm leading-relaxed text-[#e8e4d8] sm:text-base">Nhật ký đang mở tại trạm {nextStation.code}. Hoàn thành từng phép tính chính xác để nối dài tuyến đường và đánh thức guardian.</p><Link href={`/station/${nextStation.id}`} className="mt-6 inline-flex items-center gap-2 border-2 border-[#172a48] bg-[#f6b73c] px-4 py-3 text-sm font-black text-[#172a48] shadow-[3px_3px_0_white] transition hover:-translate-y-0.5 active:scale-[.98]">Đi vào trạm <ArrowRight size={17} /></Link></div><div className="absolute bottom-3 right-3 flex items-center gap-2 bg-[#fffdf6] px-2.5 py-1.5 font-mono text-[9px] font-bold tracking-[0.13em] text-[#172a48]">{nextStation.code} <span className="h-1.5 w-1.5 rounded-full bg-[#3e9b7a]" /></div></section>
    <section className="mt-8 grid gap-6 xl:grid-cols-[1.5fr_.78fr]"><article className="paper-stack relative overflow-hidden border-2 border-[#172a48] bg-[#fffdf6] p-5 shadow-[6px_6px_0_#172a48] sm:p-6"><span className="paper-tape" aria-hidden="true" /><div className="absolute right-0 top-0 h-16 w-16 border-b-2 border-l-2 border-[#172a48] bg-[#e7f2e5]" /><div className="relative"><p className="section-kicker">Nhiệm vụ đang mở</p><div className="mt-2 flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-display text-3xl font-black">{nextStation.title}</h2><p className="mt-2 max-w-xl text-sm leading-relaxed text-[#58708b]">{nextStation.brief}</p></div><span className="rounded-full border-2 border-[#172a48] bg-[#fff0b6] px-3 py-1.5 font-mono text-xs font-bold">{done}/{total}</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="evidence-card border-2 border-[#d7d0bf] bg-[#f8f3e7] p-3"><Map size={17} className="text-[#ee6b4e]" /><p className="mt-2 font-display text-2xl font-black">{completedStations}/5</p><p className="text-xs text-[#58708b]">Trạm đã làm chủ</p></div><div className="evidence-card border-2 border-[#d7d0bf] bg-[#f8f3e7] p-3"><Gem size={17} className="text-[#3e9b7a]" /><p className="mt-2 font-display text-2xl font-black">{progress.collectedGuardianIds.length}</p><p className="text-xs text-[#58708b]">Guardian đã gặp</p></div><div className="evidence-card border-2 border-[#d7d0bf] bg-[#f8f3e7] p-3"><Flame size={17} className="text-[#ee6b4e]" /><p className="mt-2 font-display text-2xl font-black">{progress.streak} ngày</p><p className="text-xs text-[#58708b]">Mạch học hiện tại</p></div></div><div className="mt-5 flex flex-wrap gap-3"><Link href="/map" className="inline-flex items-center gap-2 border-2 border-[#172a48] bg-[#fffdf6] px-4 py-3 font-bold shadow-[2px_2px_0_#172a48]">Mở bản đồ <Map size={16} /></Link><Link href="/collection" className="inline-flex items-center gap-2 border-2 border-[#172a48] bg-[#fff0b6] px-4 py-3 font-bold shadow-[2px_2px_0_#172a48]">Xem bộ sưu tập <Sparkles size={16} /></Link></div></div></article><article className="guardian-guide relative overflow-hidden border-2 border-[#172a48] bg-[#172a48] p-5 text-white shadow-[5px_5px_0_#ee6b4e]"><span className="field-tag border-white/25 bg-white/10 text-white"><Sparkles size={14} className="text-[#f6b73c]" /> Guardian sắp gặp</span><div className="mt-4 flex items-start gap-4"><GuardianSeal guardian={guardian} unlocked={false} compact progressLabel="cần hoàn thành nhiệm vụ" /><div className="min-w-0"><p className="font-mono text-[10px] tracking-[0.15em] text-[#9bb4ce]">{guardian?.type}</p><h2 className="font-display text-3xl font-black">{guardian?.name}</h2><p className="mt-3 text-sm leading-relaxed text-[#d5dfed]">{guardian?.description}</p><span className="mt-3 inline-block rounded-full bg-[#f6b73c] px-2 py-1 font-mono text-[10px] font-bold text-[#172a48]">LV.{level}</span></div></div></article></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-[1fr_.8fr]"><article className="overflow-hidden border-2 border-[#172a48] bg-[#fffdf6] shadow-[5px_5px_0_#172a48]"><div className="grid items-center gap-4 p-4 sm:grid-cols-[auto_1fr_auto] sm:p-5"><img src={STICKERS_IMAGE} alt="Sticker phần thưởng Math4Fun" className="h-20 w-20 object-contain" /><div><p className="section-kicker">Collection update</p><h2 className="font-display text-2xl font-black">Dấu ấn đến từ lời giải đúng</h2><p className="text-sm text-[#58708b]">Hoàn thành mỗi trạm để thêm guardian vào sổ. Ba nhiệm vụ đúng cũng tạo một sticker bằng chứng.</p></div><Link href="/collection" className="justify-self-start border-2 border-[#172a48] bg-[#fff0b6] px-4 py-2 text-sm font-bold shadow-[2px_2px_0_#172a48] transition hover:-translate-y-0.5">Xem collection</Link></div></article><article className="overflow-hidden border-2 border-[#172a48] bg-[#172a48] text-white shadow-[5px_5px_0_#3e9b7a]"><div className="relative h-28 overflow-hidden"><img src={ARENA_IMAGE} alt="Đấu trường Boss Atlas" className="h-full w-full object-cover opacity-70" /><div className="absolute inset-0 bg-gradient-to-t from-[#172a48] to-transparent" /><span className="absolute bottom-3 left-4 font-mono text-[10px] font-bold tracking-[0.18em] text-[#f6b73c]">BOSS RADAR</span></div><div className="flex items-center justify-between gap-3 p-4"><div><p className="font-display text-2xl font-black">Atlas {isBossUnlocked ? "đã sẵn sàng" : "đang chờ"}</p><p className="text-sm text-[#b4c6db]">{isBossUnlocked ? "Thử sức với combat theo lượt." : `Cần ${Math.max(0, 4 - completedStations)} trạm đầu nữa.`}</p></div><Link href="/boss" className="grid h-10 w-10 place-items-center rounded-full border-2 border-[#f6b73c]"><Crown size={19} className="text-[#f6b73c]" /></Link></div></article></section>
    <section className="mt-8 grid gap-4 md:grid-cols-3"><div className="evidence-note border-2 border-[#172a48] bg-[#fffdf6] p-4 shadow-[3px_3px_0_#172a48]"><Trophy className="text-[#f6b73c]" size={22} /><p className="mt-3 font-display text-2xl font-black">Cấp độ {level}</p><p className="mt-1 text-sm text-[#58708b]">XP và mở khóa được ghi lại ngay trong trình duyệt local.</p></div><div className="border-2 border-[#172a48] bg-[#fff8da] p-4 shadow-[3px_3px_0_#172a48]"><BookOpen className="text-[#ee6b4e]" size={22} /><p className="mt-3 font-display text-2xl font-black">Nguồn rõ ràng</p><p className="mt-1 text-sm text-[#58708b]">Mỗi nhiệm vụ có bài và trang PDF hiển thị trực tiếp.</p></div><div className="border-2 border-[#172a48] bg-[#e7f2e5] p-4 shadow-[3px_3px_0_#172a48]"><ShieldCheck className="text-[#3e9b7a]" size={22} /><p className="mt-3 font-display text-2xl font-black">Đáp án kiểm tra</p><p className="mt-1 text-sm text-[#58708b]">Gợi ý và lời giải được tính lại trước khi đưa vào game.</p></div></section>
  </section>;
}
