/** Field Journal Quest — evidence route: rank cards are pinned field records, not dashboard widgets. */
/** Field Journal Quest leaderboard: a shared field-score log joins rank, guardian evidence and progress on a stamped expedition record. */
import { Award, Crown, Footprints, Gem, Medal, ShieldCheck, Trophy, X } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { useGame } from "@/contexts/GameContext";
import { GUARDIANS, SHOP_ITEMS } from "@/game/gameData";
import { PlayerAvatar } from "@/components/PlayerAvatar";

const rankInk = ["bg-[#fff0b6]", "bg-[#e7f2e5]", "bg-[#e4edf7]", "bg-[#fffdf6]"];
type LeaderboardSort = "score" | "streak" | "guardians";

export default function LeaderboardPage() {
  const { leaderboard, profile, profiles } = useGame();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [sortBy, setSortBy] = useState<LeaderboardSort>("score");
  const selected = profiles.find((item) => item.id === selectedId);
  const sortedLeaderboard = useMemo(() => [...leaderboard].sort((left, right) => {
    const difference = sortBy === "streak" ? right.streak - left.streak : sortBy === "guardians" ? right.guardians - left.guardians : right.score - left.score;
    return difference || right.score - left.score || right.level - left.level || left.name.localeCompare(right.name, "vi");
  }), [leaderboard, sortBy]);
  const hasEntries = sortedLeaderboard.length > 0;
  const sealedSpecimen = GUARDIANS.find((guardian) => guardian.id === "atlas");
  return <section className="relative overflow-hidden border-2 border-[#172a48] bg-[#fffdf6] shadow-[6px_6px_0_#172a48]">
    <div className="absolute right-6 top-5 rotate-6 border-2 border-dashed border-[#172a48] bg-[#f6b73c] px-3 py-1 font-mono text-[10px] font-black tracking-[0.15em]">DEVICE LOG</div>
    <header className="relative overflow-hidden border-b-2 border-[#172a48] bg-[#e4edf7] px-5 pb-7 pt-6 sm:px-8">
      <svg aria-hidden viewBox="0 0 440 100" className="absolute bottom-0 right-0 hidden h-20 w-96 opacity-45 md:block"><path d="M0 78 C60 12 137 106 206 55 S330 18 440 30" fill="none" stroke="#172a48" strokeDasharray="4 7" strokeWidth="2"/></svg>
      <div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-full border-2 border-[#172a48] bg-[#f6b73c] shadow-[3px_3px_0_#172a48]"><Trophy size={22}/></span><div><p className="section-kicker">BẢNG CHỨNG TÍCH</p><h1 className="font-display text-3xl font-black leading-none sm:text-4xl">Đường đua trên thiết bị</h1></div></div>
      <p className="relative mt-4 max-w-2xl text-sm leading-relaxed text-[#476275]">Mỗi hồ sơ ký tên trở thành một ghim trên sổ điểm hành trình. Khi đồng bộ được bật, log có thể ghép các dấu mốc từ thiết bị khác; điểm vẫn ưu tiên bằng chứng học tập, sau đó là guardian, huy hiệu và tiến độ trạm.</p>
      <div className="relative mt-5 flex flex-wrap gap-2 text-[11px] font-bold"><span className="field-tag"><Footprints size={13}/> Điểm: câu đúng + trạm + Boss</span><span className="field-tag"><Award size={13}/> Huy hiệu là bằng chứng phụ</span><span className="field-tag"><ShieldCheck size={13}/> Field score log dùng chung</span></div>
      <div className="mt-5 flex flex-wrap items-center gap-2"><span className="font-mono text-[10px] font-black tracking-[.14em] text-[#58708b]">SẮP XẾP THEO</span>{([ ["score", "Tổng XP & điểm"], ["streak", "Chuỗi học"], ["guardians", "Guardian thu phục"] ] as const).map(([key, label]) => <button key={key} type="button" onClick={() => setSortBy(key)} className={`border-2 border-[#172a48] px-3 py-1.5 text-xs font-black shadow-[2px_2px_0_#172a48] transition active:scale-[.97] ${sortBy === key ? "bg-[#172a48] text-white" : "bg-[#fffdf6] hover:bg-[#fff0b6]"}`}>{label}</button>)}</div>
    </header>
    <div className="relative px-5 py-7 sm:px-8">
      <div aria-hidden="true" className="absolute bottom-5 left-9 top-5 border-l-2 border-dashed border-[#58708b]" />
      {!hasEntries ? <div className="relative ml-8 grid gap-5 border-2 border-dashed border-[#172a48] bg-[#fff8da] p-5 sm:grid-cols-[1fr_190px]"><div><p className="font-mono text-xs font-black tracking-[0.15em]">FIELD SCORE LOG · CHƯA CÓ DẤU CHÂN</p><h2 className="mt-2 font-display text-3xl font-black">Sổ điểm chờ chữ ký đầu tiên</h2><p className="mt-2 max-w-xl text-sm leading-relaxed text-[#476275]">Hoàn thành một câu toán để ghi điểm bằng chứng; hoàn thành trạm để thêm guardian và huy hiệu vào sổ điểm hành trình.</p><div className="mt-5 flex items-center gap-2 text-center text-[10px] font-black"><span className="border-2 border-[#172a48] bg-[#f6b73c] px-2 py-2">01<br/>KÝ TÊN</span><i className="w-7 border-t-2 border-dotted border-[#172a48]"/><span className="border-2 border-[#172a48] bg-white px-2 py-2">02<br/>GIẢI CÂU</span><i className="w-7 border-t-2 border-dotted border-[#172a48]"/><span className="border-2 border-[#172a48] bg-white px-2 py-2">03<br/>GHI ĐIỂM</span></div><Link href="/start" className="mt-5 inline-flex border-2 border-[#172a48] bg-[#f6b73c] px-4 py-2 text-sm font-black shadow-[3px_3px_0_#172a48]">Ký tên để ghi điểm đầu tiên</Link></div><aside className="rotate-[2deg] border-2 border-[#172a48] bg-[#e8f0e4] p-3 shadow-[3px_3px_0_#172a48]"><span className="field-tag">SPECIMEN R-01 · SEALED</span><div className="mx-auto mt-3 grid h-24 w-24 place-items-center rounded-full border-2 border-dashed border-[#172a48] bg-[#fffdf6]"><img src={sealedSpecimen?.sprite} alt="Tiêu bản guardian đang niêm phong" className="h-16 w-16 object-contain grayscale-[.55]"/></div><p className="mt-3 border-t border-dashed border-[#9ea99e] pt-2 font-mono text-[9px] font-bold tracking-[.12em] text-[#58708b]">ATLAS · MỐC THỨ HẠNG · MỞ KHI CÓ BẰNG CHỨNG</p></aside></div> : <ol className="relative space-y-5">{sortedLeaderboard.map((entry, index) => {
        const rank = index + 1; const isCurrent = entry.profileId === profile?.id;
        return <li key={entry.profileId} onClick={() => setSelectedId(entry.profileId)} className={`relative ml-8 grid cursor-pointer gap-4 border-2 border-[#172a48] p-4 shadow-[3px_3px_0_#172a48] before:absolute before:right-5 before:top-0 before:h-3 before:w-16 before:-translate-y-1/2 before:rotate-[2deg] before:bg-[#f6b73c]/70 before:content-[''] sm:grid-cols-[64px_1fr_auto] sm:items-center ${index % 3 === 1 ? "sm:ml-12 sm:rotate-[.35deg]" : index % 3 === 2 ? "sm:ml-6 sm:-rotate-[.3deg]" : "sm:rotate-[.15deg]"} ${rankInk[Math.min(index, 3)]} ${isCurrent ? "ring-4 ring-[#f6b73c] ring-offset-2" : ""}`}>
          <span className="absolute -left-[2.95rem] grid h-8 w-8 place-items-center rounded-full border-2 border-[#172a48] bg-[#fffdf6] font-display font-black">{rank}</span>
          <PlayerAvatar avatar={entry.avatar} name={entry.name} size="md"/>
          <div><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-2xl font-black">{entry.name}</h2>{isCurrent && <span className="field-tag bg-[#f6b73c]">HỒ SƠ CỦA EM</span>}{rank === 1 && <Crown size={19} className="text-[#d88900]"/>}</div><p className="mt-1 text-xs font-bold text-[#476275]">LV.{entry.level} · {entry.stations} trạm hoàn thành · chuỗi {entry.streak} ngày</p><div className="mt-3 flex flex-wrap gap-2 text-xs font-bold"><span className="border border-[#172a48] bg-white px-2 py-1"><Gem className="mr-1 inline" size={13}/>{entry.guardians} guardian</span><span className="border border-[#172a48] bg-white px-2 py-1"><Medal className="mr-1 inline" size={13}/>{entry.badges} huy hiệu</span><span className="border border-dashed border-[#4d8b67] bg-[#eef5f2] px-2 py-1 font-mono text-[9px] tracking-[.1em] text-[#476275]">EVIDENCE LINKED</span></div></div>
          <div className="border-2 border-[#172a48] bg-[#172a48] px-3 py-2 text-center text-white"><p className="font-mono text-[9px] font-bold tracking-[0.14em] text-[#fff0b6]">FIELD SCORE</p><p className="font-display text-2xl font-black">{entry.score}</p></div>
        </li>;
      })}</ol>}{selected && <div className="fixed inset-0 z-50 grid place-items-center bg-[#172a48]/60 p-4" onClick={() => setSelectedId(null)}><article className="w-full max-w-lg border-2 border-[#172a48] bg-[#fffdf6] p-5 shadow-[6px_6px_0_#f6b73c]" onClick={(event) => event.stopPropagation()}><button onClick={() => setSelectedId(null)} className="float-right border-2 border-[#172a48] bg-white p-1"><X size={16}/></button><p className="section-kicker">HỒ SƠ THÁM HIỂM · DEVICE LOG</p><div className="mt-2 flex items-center gap-3"><PlayerAvatar avatar={selected.avatar} name={selected.name} outfitId={selected.equippedCosmetics.outfit} trailId={selected.equippedCosmetics.trail} size="lg"/><div><h2 className="font-display text-3xl font-black">{selected.name}</h2><p className="mt-1 text-sm text-[#476275]">Chuỗi {selected.streak} ngày · {selected.gold} Gold</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="border-2 border-[#172a48] bg-[#eef1fb] p-3"><b className="font-display">Trang phục đang mặc</b><p className="mt-2 text-sm">{SHOP_ITEMS.find((item) => item.id === selected.equippedCosmetics.outfit)?.label ?? "Chưa trang bị"}</p><p className="text-sm">Dấu vết: {SHOP_ITEMS.find((item) => item.id === selected.equippedCosmetics.trail)?.label ?? "Chưa trang bị"}</p></div><div className="border-2 border-[#172a48] bg-[#e8f0e4] p-3"><b className="font-display">Guardian đã thu phục</b><div className="mt-2 flex flex-wrap gap-2">{selected.collectedGuardianIds.length ? selected.collectedGuardianIds.map((id) => { const guardian = GUARDIANS.find((item) => item.id === id); return <span key={id} className="border border-[#172a48] bg-white px-2 py-1 text-xs font-bold">{guardian?.name ?? id}</span>; }) : <span className="text-sm">Chưa có guardian</span>}</div></div></div></article></div>}
    </div>
  </section>;
}
