/**
 * Field Journal Quest map: the stitched, off-axis expedition route is the central artifact; station cards pin evidence onto it.
 */
import { Link } from "wouter";
import { useState } from "react";
import { Compass, Crown, LockKeyhole, MapPinned, MessageCircle, Sparkles } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";
import { MAPS, STATIONS, MAP_BOSS_ARCHIVES, getGuardian, getMapStations } from "@/game/gameData";
import { EXTRA_STATION_OPEN_GOLD, useGame } from "@/contexts/GameContext";
import { PlayerAvatar } from "@/components/PlayerAvatar";

const routeOffsets = [0, 29, 6, 39, 12, 44, 18, 35, 5, 31, 9, 42, 15, 37, 3, 28, 11, 40, 20, 34];

export default function MapPage() {
  const { profile, isStationUnlocked, isStationMastered, stationProgress, unlockStationForWeek, weeklyOpenCount, equippedCosmetics, isMapUnlocked, isMap1BossUnlocked, isMap2BossUnlocked } = useGame();
  const [activeMap, setActiveMap] = useState<1 | 2>(1);
  const [companionTipIndex, setCompanionTipIndex] = useState<number | null>(null);
  const stations = getMapStations(activeMap).filter((station) => station.status === "ready");
  const nextStation = stations.find((station) => isStationUnlocked(station.id) && !isStationMastered(station.id));
  const companionTips = [
    nextStation ? `Mình đã đánh dấu ${nextStation.code}. Cùng ghi đủ 10 bằng chứng nhé!` : "Mình đang dò tìm một mốc mới trên tuyến đường.",
    activeMap === 1 ? "Map 1 có 10 chủ đề. Hoàn tất tất cả để gọi Boss tổng hợp!" : "Map 2 đã mở rồi. Mỗi dấu mực mới sẽ dẫn ta gần kho lưu trữ hơn.",
    "Gợi ý nhỏ: đúng 5 câu liên tiếp sẽ nhận thêm 5 Gold ngoài Gold theo độ khó.",
  ];

  if (!profile) return <section>
    <p className="section-kicker"><MapPinned size={13} /> MAP 1 · BẢN ĐỒ XEM TRƯỚC</p>
    <h1 className="font-display text-4xl font-black">Một tuyến đường đang chờ chữ ký</h1><p className="mt-2 max-w-3xl text-sm text-[#58708b]">Map 1 gom 10 chủ đề Toán 4 Tập 1. Hoàn tất hành trình để gọi Boss tổng hợp và mở Map 2 của Tập 2.</p>
    <RouteArtifact stations={getMapStations(1).filter((station) => station.status === "ready").slice(0, 5)} profile={null} isStationUnlocked={() => false} isStationMastered={() => false} stationProgress={() => ({ correct: 0, answered: 0, target: 10, total: 10, accuracy: 0 })} onOpen={() => false} freeOpenAvailable={false} nextStationId={undefined} />
    <div className="mt-4 border-2 border-dashed border-[#172a48] bg-[#fff8da] p-4"><b className="font-display text-xl">Hai lượt mở chủ đề mỗi tuần sẽ được ghi ở đây.</b><p className="mt-1 text-sm text-[#58708b]">Tạo sổ trước, sau đó chọn một tuyến để bắt đầu ghi bằng chứng.</p><Link href="/start" className="mt-4 inline-flex border-2 border-[#172a48] bg-[#f6b73c] px-4 py-2 font-bold shadow-[3px_3px_0_#172a48]">Ký tên vào bản đồ</Link></div>
  </section>;

  return <section>
    <div className="grid gap-4 xl:grid-cols-[1fr_270px] xl:items-end"><div><p className="section-kicker"><MapPinned size={13} /> {MAPS[activeMap].label} · {weeklyOpenCount}/2 OPEN MIỄN PHÍ</p><h1 className="font-display text-4xl font-black">{MAPS[activeMap].title}</h1><p className="mt-2 max-w-3xl text-sm text-[#58708b]">{MAPS[activeMap].note} Mỗi tuần có 2 lượt ký mở miễn phí; sau đó vẫn có thể mở mốc mới bằng {EXTRA_STATION_OPEN_GOLD} Gold. Đường nét vàng chỉ nơi cần bước tiếp; đừng bỏ qua bằng chứng đang ghi dở.</p></div><aside className="relative border-2 border-[#172a48] bg-[#fffdf6] p-3 shadow-[3px_3px_0_#172a48]"><button type="button" onClick={() => setCompanionTipIndex((current) => current === null ? 0 : (current + 1) % companionTips.length)} className="flex w-full items-center gap-3 text-left" aria-label="Nghe lời nhắc từ companion"><motion.span animate={companionTipIndex !== null ? { y: [0, -4, 0], rotate: [0, -2, 2, 0] } : { y: 0, rotate: 0 }} transition={{ duration: .42 }}><PlayerAvatar avatar={profile.avatar} name={profile.name} outfitId={equippedCosmetics.outfit} trailId={equippedCosmetics.trail} size="sm"/></motion.span><span><span className="font-mono text-[9px] font-black tracking-[.15em] text-[#58708b]">COMPANION ĐỒNG HÀNH</span><b className="block font-display text-lg">{profile.name}</b><span className="block text-[11px] text-[#4d8b67]">{nextStation ? `Đang hướng tới ${nextStation.code}` : "Đang tìm mốc mới"}</span><span className="mt-1 inline-flex items-center gap-1 text-[10px] font-bold text-[#a46b15]"><MessageCircle size={11}/> Chạm để nghe chỉ dẫn</span></span></button><AnimatePresence>{companionTipIndex !== null && <motion.div initial={{ opacity: 0, y: 7, scale: .96 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 4, scale: .97 }} className="absolute right-2 top-[calc(100%+7px)] z-30 w-64 border-2 border-[#172a48] bg-[#fff0b6] p-3 text-xs font-semibold leading-relaxed text-[#172a48] shadow-[3px_3px_0_#172a48]"><span className="absolute -top-2 right-9 h-3 w-3 rotate-45 border-l-2 border-t-2 border-[#172a48] bg-[#fff0b6]"/>{companionTips[companionTipIndex]}<button type="button" onClick={() => setCompanionTipIndex(null)} className="mt-2 block text-[10px] font-black uppercase tracking-[.12em] text-[#4d8b67] underline">Gấp lời nhắn</button></motion.div>}</AnimatePresence></aside></div>
    <div className="mt-5 flex flex-wrap gap-3" role="tablist" aria-label="Chọn bản đồ học"><button onClick={() => setActiveMap(1)} className={`border-2 border-[#172a48] px-4 py-2 text-left shadow-[2px_2px_0_#172a48] ${activeMap === 1 ? "bg-[#f6b73c]" : "bg-[#fffdf6]"}`}><b className="font-display">MAP 1 · Tập 1</b><span className="ml-2 text-xs">10 chủ đề + Boss</span></button><button onClick={() => isMapUnlocked(2) && setActiveMap(2)} disabled={!isMapUnlocked(2)} className={`border-2 border-[#172a48] px-4 py-2 text-left shadow-[2px_2px_0_#172a48] disabled:cursor-not-allowed disabled:bg-[#e6e0cf] ${activeMap === 2 ? "bg-[#f6b73c]" : "bg-[#fffdf6]"}`}><b className="font-display">{isMapUnlocked(2) ? "MAP 2 · Tập 2" : "MAP 2 · NIÊM PHONG"}</b><span className="ml-2 text-xs">{isMapUnlocked(2) ? "10 chủ đề mới" : "Thắng Boss Map 1 để mở"}</span></button></div>
    {nextStation && <aside className="relative mt-5 max-w-xl rotate-[-1deg] border-2 border-[#172a48] bg-[#fff0b6] px-4 py-3 shadow-[4px_4px_0_#172a48]"><span className="absolute -left-3 top-1/2 grid h-7 w-7 -translate-y-1/2 place-items-center rounded-full border-2 border-[#172a48] bg-[#f6b73c]"><Compass size={14}/></span><p className="ml-4 font-mono text-[9px] font-black tracking-[.15em]">LA BÀN MARIGOLD · ĐIỂM ĐẾN KẾ TIẾP</p><p className="ml-4 mt-1 text-sm"><b className="font-display text-lg">{nextStation.code} · {nextStation.title}</b> đang là bằng chứng cần được ghi tiếp trên tuyến này.</p></aside>}
    <RouteArtifact stations={stations} profile={profile} isStationUnlocked={isStationUnlocked} isStationMastered={isStationMastered} stationProgress={stationProgress} onOpen={unlockStationForWeek} freeOpenAvailable={weeklyOpenCount < 2} nextStationId={nextStation?.id} />
    <BossGateArtifact mapId={activeMap} bossUnlocked={activeMap === 1 ? isMap1BossUnlocked : isMap2BossUnlocked} bossDefeated={activeMap === 1 ? profile.map1BossDefeated : profile.map2BossDefeated} openedCount={stations.filter((station) => isStationUnlocked(station.id)).length} />
  </section>;
}

function RouteArtifact({ stations, profile, isStationUnlocked, isStationMastered, stationProgress, onOpen, freeOpenAvailable, nextStationId }: { stations: typeof STATIONS; profile: ReturnType<typeof useGame>["profile"]; isStationUnlocked: (stationId: number) => boolean; isStationMastered: (stationId: number) => boolean; stationProgress: ReturnType<typeof useGame>["stationProgress"]; onOpen: (stationId: number) => boolean; freeOpenAvailable: boolean; nextStationId?: number }) {
  return <div className="route-artifact route-artifact--terrain relative mt-6 overflow-hidden border-2 border-[#172a48] bg-[#e8f0e4] p-5 shadow-[6px_6px_0_#172a48]" style={{ backgroundImage: "linear-gradient(#c9d5c7 1px, transparent 1px), linear-gradient(90deg, #c9d5c7 1px, transparent 1px)", backgroundSize: "22px 22px" }}>
    <div className="absolute left-4 top-4 rotate-[-3deg] border-2 border-[#172a48] bg-[#fff0b6] px-2 py-1 font-mono text-[9px] font-black tracking-[.14em] shadow-[2px_2px_0_#172a48]">ROUTE THREAD · {profile ? "LIVE" : "SEALED"}</div>
    <div className="route-annotation route-annotation-start">ĐIỂM XUẤT PHÁT · LA BÀN</div><div className="route-annotation route-annotation-end">DẤU TIẾP THEO · THEO ĐƯỜNG CHỈ</div>
    <svg className="route-thread pointer-events-none absolute inset-x-0 top-8 h-[calc(100%-4rem)] w-full opacity-80" viewBox="0 0 100 1000" preserveAspectRatio="none" aria-hidden="true"><path d="M 7 22 C 82 55 15 84 83 126 S 9 192 79 230 S 17 301 88 345 S 7 415 79 465 S 20 545 89 592 S 11 665 78 714 S 16 800 86 840 S 10 910 75 965" fill="none" stroke="#2b6f69" strokeWidth="1.35" strokeDasharray="1 1.15"/><path d="M 7 22 C 82 55 15 84 83 126" fill="none" stroke="#f6b73c" strokeWidth="1.75" strokeDasharray="1 1.15"/></svg>
    <div className="relative z-10 mt-12 space-y-5 pb-4">{stations.map((station, index) => {
      const guardian = getGuardian(station.guardianId); const guardianArtwork = guardian ? `/guardians/${guardian.id}.webp` : null; const unlocked = isStationUnlocked(station.id); const mastered = isStationMastered(station.id); const progress = stationProgress(station.id); const isNext = station.id === nextStationId; const offset = routeOffsets[index % routeOffsets.length];
      return <motion.article key={station.id} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: Math.min(index * 0.025, .36) }} style={{ marginLeft: `min(${offset}%, 300px)`, rotate: `${[-0.8, 0.6, -0.35, 0.9, -0.55][index % 5]}deg` }} className={`route-pinned-note route-pinned-note--${index % 8} relative max-w-[390px] border-2 border-[#172a48] bg-[#fffdf6] p-3.5 shadow-[4px_4px_0_#172a48] lg:max-w-[430px] ${isNext ? "ring-4 ring-[#f6b73c] ring-offset-2" : ""}`}>
        <span aria-hidden className={`absolute -top-2 ${index % 2 ? "right-7" : "left-8"} h-4 w-4 rotate-45 border-2 border-[#172a48] ${isNext ? "bg-[#f6b73c]" : "bg-[#eef1fb]"}`} />
        <span className={`absolute -left-7 top-1/2 grid h-10 w-10 -translate-y-1/2 place-items-center rounded-full border-2 border-[#172a48] ${mastered ? "bg-[#9dba70]" : isNext ? "bg-[#f6b73c]" : "bg-[#eef1fb]"}`}><Compass size={17}/></span>
        <div className="flex gap-3"><div className="min-w-0 flex-1"><p className="font-mono text-[10px] font-black tracking-[.13em] text-[#58708b]">{station.code} · {mastered ? "BẰNG CHỨNG ĐỦ" : unlocked ? "ĐANG GHI" : "MỐC ĐÃ NIÊM"}</p><h2 className="mt-1 font-display text-2xl font-black">{station.title}</h2><p className="mt-1 text-xs text-[#58708b]">Guardian {guardian?.name ?? "niêm phong"} · {mastered ? "Đã thu phục" : `${progress.correct}/10 bằng chứng`}</p><div className="mt-2 flex flex-wrap gap-1"><span className="field-tag bg-[#eef1fb] text-[9px] text-[#172a48]">MẪU VẬT · {guardian?.element ?? "SEALED"}</span><span className="field-tag bg-[#fff8da] text-[9px] text-[#172a48]">{mastered ? "DẤU ĐỦ" : unlocked ? "DẤU ĐANG GHI" : "ẤN NIÊM PHONG"}</span></div></div><div className="guardian-stamp grid h-28 w-28 shrink-0 place-items-center overflow-hidden rounded-full border-2 border-[#172a48] bg-transparent p-1">{guardianArtwork ? <img src={guardianArtwork} alt={`Guardian ${guardian?.name ?? ""}`} className="h-[88%] w-[88%] rounded-full object-contain [clip-path:circle(48%)]"/> : <LockKeyhole size={30}/>}</div></div>
        <div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t-2 border-dashed border-[#d7d0bf] pt-3">{isNext && <span className="field-tag bg-[#fff0b6] text-[#172a48]"><Sparkles size={12}/> MỐC KẾ TIẾP</span>}<span className="text-xs font-bold text-[#4d8b67]">{mastered ? "Dấu mực hoàn tất" : unlocked ? "Tuyến đã mở" : freeOpenAvailable ? "Chờ ký mở miễn phí" : `Mở thêm · ${EXTRA_STATION_OPEN_GOLD} Gold`}</span>{unlocked ? <Link href={`/station/${station.id}`} className="border-2 border-[#172a48] bg-white px-3 py-2 text-xs font-black shadow-[2px_2px_0_#172a48]">{mastered ? "Xem trạm" : "Ghi bằng chứng"}</Link> : <button disabled={!profile || (!freeOpenAvailable && profile.gold < EXTRA_STATION_OPEN_GOLD)} onClick={() => onOpen(station.id)} className="border-2 border-[#172a48] bg-[#f6b73c] px-3 py-2 text-xs font-black shadow-[2px_2px_0_#172a48] disabled:cursor-not-allowed disabled:bg-[#d7d0bf] disabled:opacity-80">{profile ? freeOpenAvailable ? "Mở mốc" : `Mở · ${EXTRA_STATION_OPEN_GOLD} Gold` : "Niêm phong"}</button>}</div>
      </motion.article>;
    })}</div>
  </div>;
}

function BossGateArtifact({ mapId, bossUnlocked, bossDefeated, openedCount }: { mapId: 1 | 2; bossUnlocked: boolean; bossDefeated: boolean; openedCount: number }) {
  const boss = MAP_BOSS_ARCHIVES[mapId];
  const href = mapId === 1 ? "/map-boss" : "/map2-boss";
  const bossArtwork = mapId === 1 ? "/guardians/atlas.webp" : "/guardians/myrion.webp";
  return <article className={`relative mt-6 overflow-hidden border-2 border-[#172a48] p-5 shadow-[5px_5px_0_#172a48] ${bossUnlocked ? "bg-[#172a48] text-white" : "bg-[#fff8da]"}`}><div className="absolute bottom-3 right-3 grid h-40 w-40 place-items-center overflow-hidden rounded-full bg-transparent"><img src={bossArtwork} alt={boss.name} className={`h-[90%] w-[90%] rounded-full object-contain [clip-path:circle(48%)] ${bossUnlocked ? "opacity-100" : "grayscale opacity-45"}`} /></div><div className="relative max-w-[75%]"><p className="section-kicker text-inherit"><Crown size={13} /> CỬA CUỐI MAP {mapId} · {openedCount}/10 CHỦ ĐỀ ĐÃ MỞ</p><h2 className="mt-2 font-display text-3xl font-black">{boss.name} · {boss.title}</h2><p className={`mt-2 text-sm ${bossUnlocked ? "text-[#d5dfed]" : "text-[#58708b]"}`}>{bossDefeated ? `Huy hiệu ${boss.badge} đã được đóng dấu.` : bossUnlocked ? `Cả 10 chủ đề Map ${mapId} đã mở. Chọn guardian và bước vào trận 10 câu M/H.` : `Mở đủ 10 chủ đề Map ${mapId} để phá ấn ${boss.name}; mỗi cửa Boss trao huy hiệu riêng.`}</p></div><div className="relative mt-4 flex max-w-[75%] flex-wrap gap-2 border-t border-dashed border-current/40 pt-3"><span className="field-tag bg-[#fffdf6] text-[#172a48]">01 · 10 MỐC ĐÃ MỞ</span><span className="field-tag bg-[#fffdf6] text-[#172a48]">02 · 10 CÂU M/H</span><span className="field-tag bg-[#fff0b6] text-[#172a48]"><Crown size={12}/> 03 · {boss.badge}</span></div>{bossDefeated ? <span className="relative mt-4 inline-flex field-tag bg-[#9dba70] text-[#172a48]"><Crown size={12}/> {boss.badge}</span> : <Link href={href} className={`relative mt-4 inline-flex items-center gap-2 border-2 border-[#172a48] px-4 py-3 font-black shadow-[3px_3px_0_#f6b73c] ${bossUnlocked ? "bg-[#f6b73c] text-[#172a48]" : "pointer-events-none bg-[#d7d0bf] text-[#58708b]"}`}><Crown size={16} /> Vào Boss Map {mapId}</Link>}</article>;
}
