/** Field Journal Quest profile dossier: a signed-in learner's personal evidence record. */
import { Link } from "wouter";
import { Award, BookOpenCheck, CalendarDays, ChevronRight, Compass, ShieldCheck, Sparkles, Swords, UserRound } from "lucide-react";
import { PlayerAvatar } from "@/components/PlayerAvatar";
import { GUARDIANS } from "@/game/gameData";
import { useGame } from "@/contexts/GameContext";

export default function ProfilePage() {
  const { profile, level, levelProgress, getGuardianTrainingHistory, isAdmin } = useGame();
  if (!profile) { const pendingGuardian = GUARDIANS.find((guardian) => guardian.id === "atlas") ?? GUARDIANS[0]; return <section className="stats-blank-dossier"><header className="grid gap-5 lg:grid-cols-[1fr_230px]"><div><p className="section-kicker"><UserRound size={13}/> HỒ SƠ CÁ NHÂN · CHỜ KÝ TÊN</p><h1 className="font-display text-4xl font-black">Trang lý lịch đang chờ chủ nhân</h1><p>Chưa có chữ ký nào trên trang đầu. Khi em lập hồ sơ, mọi đáp án, companion và huy hiệu sẽ được đóng dấu vào đúng nhật ký của em.</p></div><aside className="rotate-[2deg] border-2 border-[#172a48] bg-[#eef1fb] p-3 shadow-[3px_3px_0_#172a48]"><span className="field-tag">PROFILE SPECIMEN · LOCKED</span><div className="mx-auto mt-2 grid h-28 w-28 place-items-center rounded-full border-2 border-dashed border-[#172a48] bg-[#fffdf6]"><img src={pendingGuardian.sprite} alt="Tiêu bản Atlas niêm phong" className="h-20 w-20 object-contain grayscale-[.6]"/></div><p className="mt-2 border-t border-dashed border-[#9ea99e] pt-2 font-mono text-[9px] font-bold tracking-[.12em] text-[#58708b]">ATLAS · HỒ SƠ HỘ VỆ · CHỜ CHỮ KÝ</p></aside></header><div className="stats-blank-route"><span className="is-active">01<br/><small>Ký tên</small></span><i/><span>02<br/><small>Ghi đáp án</small></span><i/><span>03<br/><small>Gặp guardian</small></span><i/><span>04<br/><small>Nhận huy hiệu</small></span></div><div className="stats-blank-evidence"><article><p className="section-kicker">BẰNG CHỨNG CÒN THIẾU</p><b>01 chữ ký nhật ký</b><small>tạo tên đăng nhập và mật khẩu riêng trên máy này</small></article><article className="stats-blank-seal"><Award size={27}/><b>Huy hiệu chờ đóng</b><small>mở bằng các lời giải đúng, không phải chỉ bằng lượt truy cập</small></article><article className="border-2 border-dashed border-[#172a48] bg-[#fff8da] p-4"><p className="section-kicker">MỐC KẾ TIẾP</p><b>Chọn một companion</b><small>để hồ sơ ghi nhận trang phục và hành trình đi cùng em</small></article></div><Link href="/start" className="stats-blank-cta">Ký tên để mở trang lý lịch</Link></section>; }
  const trainingHistory = profile.teamGuardianIds.flatMap((id) => getGuardianTrainingHistory(id));
  const earnedTechniques = Math.max(0, Math.max(...profile.teamGuardianIds.map((id) => profile.guardianTrainingXp[id] ?? 0), 0));
  return <div className="space-y-6">
    <section className="relative overflow-hidden border-2 border-[#172a48] bg-[#172a48] p-5 text-white shadow-[5px_5px_0_#f6b73c] sm:p-7"><div className="absolute -right-8 -top-10 h-44 w-44 rounded-full border-[18px] border-[#f6b73c]/20"/><div className="relative flex flex-col gap-5 sm:flex-row sm:items-center"><div className="border-2 border-[#fffdf6] bg-[#eef1fb] p-2 shadow-[4px_4px_0_#f6b73c]"><PlayerAvatar avatar={profile.avatar} name={profile.name} outfitId={profile.equippedCosmetics.outfit} trailId={profile.equippedCosmetics.trail} size="lg"/></div><div className="min-w-0"><p className="font-mono text-[10px] font-bold tracking-[.18em] text-[#f6b73c]">HỒ SƠ CÁ NHÂN · FIELD ID</p><h1 className="mt-1 truncate font-display text-4xl font-black">{profile.name}</h1><p className="mt-2 text-sm text-[#dbe5ff]">@{profile.username} · gia nhập {new Date(profile.createdAt).toLocaleDateString("vi-VN")}</p><div className="mt-4 flex flex-wrap gap-2"><span className="border border-[#f6b73c] bg-[#263b60] px-2 py-1 text-xs font-bold">LV.{level} · {levelProgress}/250 XP</span><span className="border border-[#a9d8c5] bg-[#1f594d] px-2 py-1 text-xs font-bold">Chuỗi học {profile.streak} ngày</span>{isAdmin && <span className="border border-[#fffdf6] bg-[#f6b73c] px-2 py-1 text-xs font-black text-[#172a48]">QUẢN TRỊ CỤC BỘ</span>}</div></div></div></section>
    <section className="grid gap-4 md:grid-cols-3"><article className="border-2 border-[#172a48] bg-[#fffdf6] p-4 shadow-[3px_3px_0_#172a48]"><BookOpenCheck className="text-[#3e9b7a]"/><p className="mt-4 font-mono text-[10px] font-bold tracking-[.16em] text-[#58708b]">BẰNG CHỨNG</p><p className="font-display text-3xl font-black">{profile.correctQuestionIds.length}</p><p className="text-xs text-[#58708b]">câu trả lời đúng đã ghi</p></article><article className="border-2 border-[#172a48] bg-[#fffdf6] p-4 shadow-[3px_3px_0_#172a48]"><Award className="text-[#e28b2f]"/><p className="mt-4 font-mono text-[10px] font-bold tracking-[.16em] text-[#58708b]">GUARDIAN</p><p className="font-display text-3xl font-black">{profile.collectedGuardianIds.length}/{GUARDIANS.length}</p><p className="text-xs text-[#58708b]">đã thu phục</p></article><article className="border-2 border-[#172a48] bg-[#fffdf6] p-4 shadow-[3px_3px_0_#172a48]"><Swords className="text-[#ee6b4e]"/><p className="mt-4 font-mono text-[10px] font-bold tracking-[.16em] text-[#58708b]">VÕ ĐÀI</p><p className="font-display text-3xl font-black">{trainingHistory.length}</p><p className="text-xs text-[#58708b]">trận đã lưu trong nhật ký</p></article></section>
    <section className="border-2 border-[#172a48] bg-[#fffdf6] p-5 shadow-[4px_4px_0_#172a48]"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="section-kicker">THẺ NHẮC HÀNH TRÌNH</p><h2 className="font-display text-2xl font-black">Nhật ký của {profile.name}</h2></div><Compass className="text-[#e28b2f]" size={30}/></div><div className="mt-5 grid gap-3 md:grid-cols-2"><Link href="/stats" className="group flex items-center justify-between border-2 border-dashed border-[#172a48] bg-[#eef1fb] p-4 hover:bg-[#dbe5ff]"><span><b className="block">Báo cáo tiến trình</b><small className="text-[#58708b]">Huy hiệu, Gold và sao lưu hồ sơ</small></span><ChevronRight className="transition group-hover:translate-x-1"/></Link><Link href="/study-calendar" className="group flex items-center justify-between border-2 border-dashed border-[#172a48] bg-[#fff8da] p-4 hover:bg-[#fff0b6]"><span><b className="block">Lịch học & chuỗi ngày</b><small className="text-[#58708b]">Đặt nhịp ghi bằng chứng mỗi tuần</small></span><CalendarDays className="transition group-hover:translate-x-1"/></Link><Link href="/training" className="group flex items-center justify-between border-2 border-dashed border-[#172a48] bg-[#e7f2e5] p-4 hover:bg-[#cde8df]"><span><b className="block">Tiến trình Huấn luyện</b><small className="text-[#58708b]">{earnedTechniques} XP guardian cao nhất trong đội</small></span><Sparkles className="transition group-hover:translate-x-1"/></Link><div className="flex items-center gap-3 border-2 border-dashed border-[#172a48] bg-[#fffdf6] p-4"><ShieldCheck className="shrink-0 text-[#3e9b7a]"/><p className="text-sm leading-relaxed">Phiên đăng nhập của em được ghi nhớ trên trình duyệt này cho tới khi em chọn <b>Đăng xuất</b>.</p></div></div></section>
  </div>;
}
