/** Field Journal Quest — supply shop: pinned route receipts, practical healing supplies, no commercial currency. */
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { Coins, HeartPulse, PackageOpen, Plus, Shirt, ShoppingBag, Sparkles, WandSparkles } from "lucide-react";
import { GUARDIANS, SHOP_ITEMS } from "@/game/gameData";
import { useGame } from "@/contexts/GameContext";

export default function ShopPage() {
  const { profile, gold, inventory, guardianHp, purchaseItem, useHealingItem, equippedCosmetics, equipCosmetic } = useGame();
  const owned = useMemo(() => profile ? GUARDIANS.filter((guardian) => profile.collectedGuardianIds.includes(guardian.id)) : [], [profile]);
  const [selectedGuardian, setSelectedGuardian] = useState("");
  const [message, setMessage] = useState("");
  if (!profile) { const dexo = GUARDIANS.find((guardian) => guardian.id === "dexo"); return <section className="stats-blank-dossier"><header className="grid gap-5 lg:grid-cols-[1fr_230px]"><div><p className="section-kicker">QUẦY TIẾP TẾ · CHỜ KÝ TÊN</p><h1 className="font-display text-4xl font-black">Shop chỉ mở cho nhật ký đã niêm phong.</h1><p>Tạo hoặc vào hồ sơ để nhận Gold từ mỗi câu trả lời, rồi đổi lấy bình hồi phục guardian.</p></div><aside className="relative rotate-[2deg] overflow-hidden border-2 border-[#172a48] bg-[#fff8da] p-3 shadow-[3px_3px_0_#172a48]"><span className="field-tag">SPECIMEN 01 · PENDING</span><div className="mx-auto mt-2 grid h-28 w-28 place-items-center rounded-full border-2 border-dashed border-[#172a48] bg-[#e8f0e4]"><img src={dexo?.sprite} alt="Tiêu bản Dexo đang niêm phong" className="h-20 w-20 object-contain grayscale-[.45]"/></div><p className="mt-2 border-t border-dashed border-[#a99870] pt-2 font-mono text-[9px] font-bold tracking-[.12em] text-[#58708b]">DEXO · SẤM · PHIẾU HỒI PHỤC</p></aside></header><div className="mt-5 grid gap-5 lg:grid-cols-[1fr_230px]"><div><div className="stats-blank-route"><span className="is-active">01<br/><small>Vào game</small></span><i/><span>02<br/><small>Nhận Gold</small></span><i/><span>03<br/><small>Tiếp tế</small></span></div><div className="mt-5 border-y-2 border-dashed border-[#d7d0bf] bg-[#fff8da] p-4"><p className="section-kicker">PHIẾU ĐỔI THƯỞNG</p><p className="mt-1 text-sm leading-relaxed text-[#476275]">Một lời giải đúng → Gold được đóng dấu → bình hồi phục được ghi vào kho. Tuyến tiếp tế sẽ sáng lên sau khi em ký tên vào nhật ký.</p></div></div><aside className="border-2 border-dashed border-[#172a48] bg-[#172a48] p-4 text-white"><p className="font-mono text-[10px] font-bold tracking-[.15em] text-[#f6b73c]">LÔ HÀNG ĐẦU TUYẾN</p><b className="mt-3 block font-display text-2xl">3 loại bình hồi phục</b><small className="mt-2 block leading-relaxed text-[#d5dfed]">Lộ Sáng 25% · Trưa Hè 50% · Trăng Rằm 100%</small></aside></div><Link href="/start" className="stats-blank-cta">Ký tên để mở quầy tiếp tế</Link></section>; }
  const activeId = selectedGuardian || owned[0]?.id || "";
  const activeGuardian = owned.find((guardian) => guardian.id === activeId);
  const hp = activeGuardian ? guardianHp(activeGuardian.id) : 0;
  return <section>
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-kicker">QUẦY TIẾP TẾ · GOLD LOCAL</p><h1 className="font-display text-4xl font-black">Shop & Kho đồ</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-[#58708b]">Gold nhận được khi trả lời câu hỏi. Đổi lấy bình hồi phục, trang phục và dấu vết riêng cho companion của em.</p></div><div className="border-2 border-[#172a48] bg-[#fff0b6] px-4 py-3 font-display text-3xl font-black shadow-[3px_3px_0_#172a48]"><Coins className="mr-2 inline text-[#b17a3d]" size={24}/>{gold} <span className="font-sans text-sm">Gold</span></div></header>
    <div className="mt-5 flex flex-wrap items-center gap-2 border-y-2 border-dashed border-[#c9b88c] bg-[#fff8da] px-3 py-2 font-mono text-[10px] font-bold tracking-[.13em] text-[#476275]"><span className="border border-[#172a48] bg-[#f6b73c] px-2 py-1 text-[#172a48]">BẰNG CHỨNG ĐÚNG</span><i className="w-7 border-t-2 border-dotted border-[#172a48]"/><span className="border border-[#172a48] bg-white px-2 py-1">GOLD</span><i className="w-7 border-t-2 border-dotted border-[#172a48]"/><span className="border border-[#172a48] bg-white px-2 py-1">PHIẾU BÌNH HỒI PHỤC</span><i className="w-7 border-t-2 border-dotted border-[#172a48]"/><span className="border border-[#172a48] bg-[#e8f0e4] px-2 py-1">GUARDIAN SẴN SÀNG</span></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_330px]"><section className="paper-stack border-2 border-[#172a48] bg-[#fffdf6] p-5 shadow-[5px_5px_0_#172a48]"><div className="flex items-center gap-2"><ShoppingBag size={19}/><h2 className="font-display text-3xl font-black">Sổ hàng tiếp tế</h2></div><div className="mt-5 grid gap-4 md:grid-cols-3">{SHOP_ITEMS.map((item) => <article key={item.id} className={`relative overflow-hidden border-2 border-[#172a48] p-4 shadow-[3px_3px_0_#172a48] ${item.tone}`}><span className="absolute -right-3 -top-4 text-7xl opacity-20">{item.icon}</span>{item.kind === "healing" ? <HeartPulse className="relative text-[#ee6b4e]"/> : item.slot === "outfit" ? <Shirt className="relative text-[#57518d]"/> : <WandSparkles className="relative text-[#4d8b67]"/>}<p className="relative mt-5 font-display text-2xl font-black">{item.label}</p><p className="relative mt-1 min-h-10 text-xs leading-relaxed text-[#476275]">{item.description}</p><div className="relative mt-5 flex items-center justify-between"><b><Coins className="mr-1 inline" size={14}/>{item.price}</b><button onClick={() => setMessage(purchaseItem(item.id).message)} className="border-2 border-[#172a48] bg-white px-3 py-2 text-xs font-black shadow-[2px_2px_0_#172a48] active:translate-y-px"><Plus className="mr-1 inline" size={13}/>{item.kind === "cosmetic" && inventory[item.id] ? "Đã có" : "Mua"}</button></div></article>)}</div><p className="mt-5 border-t-2 border-dashed border-[#d7d0bf] pt-4 text-xs font-bold text-[#58708b]">Trang phục và dấu vết chỉ thay đổi diện mạo companion; bình hồi phục chỉ có thể dùng ngoài trận Boss.</p></section>
      <aside className="border-2 border-[#172a48] bg-[#172a48] p-5 text-white shadow-[4px_4px_0_#f6b73c]"><PackageOpen className="text-[#f6b73c]"/><p className="mt-3 text-xs font-bold tracking-[.15em] text-[#f6b73c]">KHO ĐỒ CÁ NHÂN</p>{SHOP_ITEMS.map((item) => <div className="mt-3 flex justify-between border-b border-dashed border-white/25 pb-2 text-sm" key={item.id}><span>{item.label}</span><b>× {inventory[item.id]}</b></div>)}<p className="mt-5 text-xs leading-relaxed text-[#d5dfed]">Trang phục đã trang bị: <strong>{SHOP_ITEMS.find((item) => item.id === equippedCosmetics.outfit)?.label ?? "Chưa chọn"}</strong><br/>Dấu vết: <strong>{SHOP_ITEMS.find((item) => item.id === equippedCosmetics.trail)?.label ?? "Chưa chọn"}</strong></p></aside></div>
    <section className="mt-6 border-2 border-[#172a48] bg-[#eef1fb] p-5 shadow-[4px_4px_0_#172a48]"><p className="section-kicker">TỦ TRANG PHỤC · COMPANION</p><h2 className="font-display text-3xl font-black">Đeo dấu hiệu cho hành trình</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{SHOP_ITEMS.filter((item) => item.kind === "cosmetic").map((item) => { const isEquipped = equippedCosmetics[item.slot!] === item.id; return <article key={item.id} className="flex items-center justify-between gap-3 border-2 border-[#172a48] bg-[#fffdf6] p-3"><div><b className="font-display text-xl">{item.icon} {item.label}</b><p className="mt-1 text-xs text-[#476275]">{inventory[item.id] ? "Đã lưu trong Kho đồ." : "Chưa mua tại Shop."}</p></div><button disabled={!inventory[item.id]} onClick={() => setMessage(equipCosmetic(item.id).message)} className={`border-2 border-[#172a48] px-3 py-2 text-xs font-black shadow-[2px_2px_0_#172a48] disabled:opacity-40 ${isEquipped ? "bg-[#f6b73c]" : "bg-white"}`}>{isEquipped ? "Đang dùng" : "Trang bị"}</button></article>; })}</div></section>
    <section className="mt-6 border-2 border-[#172a48] bg-[#e8f0e4] p-5 shadow-[5px_5px_0_#172a48]"><div className="flex items-center gap-2"><HeartPulse size={18}/><div><p className="section-kicker">PHIẾU CHĂM SÓC GUARDIAN</p><h2 className="font-display text-3xl font-black">Hồi sinh lực đội của em</h2></div></div>{owned.length === 0 ? <p className="mt-4 border-2 border-dashed border-[#172a48] bg-[#fffdf6] p-4 text-sm">Em chưa có guardian nào trong Bộ sưu tập. Hoàn thành một trạm để thu phục bạn đồng hành đầu tiên.</p> : <><div className="mt-5 flex gap-3 overflow-x-auto pb-2">{owned.map((guardian) => { const currentHp = guardianHp(guardian.id); return <button key={guardian.id} onClick={() => setSelectedGuardian(guardian.id)} className={`min-w-36 border-2 border-[#172a48] p-2 text-left shadow-[2px_2px_0_#172a48] ${guardian.id === activeId ? "bg-[#172a48] text-white" : "bg-[#fffdf6]"}`}><img src={guardian.sprite} alt="" className="mx-auto h-16 w-16 object-contain"/><b className="mt-1 block text-sm">{guardian.name}</b><small className={guardian.id === activeId ? "text-[#f6b73c]" : "text-[#58708b]"}>{currentHp}/100 HP</small></button>; })}</div>{activeGuardian && <div className="mt-5 flex flex-wrap items-center justify-between gap-4 border-2 border-[#172a48] bg-[#fffdf6] p-4"><div><b className="font-display text-2xl">{activeGuardian.name}</b><p className="mt-1 text-sm text-[#476275]">Sinh lực tự hồi <strong>20 HP mỗi giờ</strong> từ lần bị sát thương gần nhất.</p><div className="mt-3 h-3 w-64 max-w-full overflow-hidden border border-[#172a48] bg-[#f5efdf]"><div className="h-full bg-[#ee6b4e]" style={{width: `${hp}%`}}/></div></div><div className="flex flex-wrap gap-2">{SHOP_ITEMS.filter((item) => item.kind === "healing").map((item) => <button key={item.id} onClick={() => setMessage(useHealingItem(item.id, activeGuardian.id).message)} disabled={!inventory[item.id]} className="border-2 border-[#172a48] bg-[#f6b73c] px-3 py-2 text-xs font-black shadow-[2px_2px_0_#172a48] disabled:opacity-40">Dùng {item.heal} HP</button>)}</div></div>}</>}{message && <p className="mt-4 flex items-center gap-2 border border-[#244e4a] bg-[#fffdf6] p-3 text-sm font-bold text-[#244e4a]" role="status"><Sparkles size={15}/>{message}</p>}</section>
  </section>;
}
