/** Field Journal Quest — account desk with collectible junior-explorer cards. */
import { FormEvent, useState } from "react";
import { Link, useLocation } from "wouter";
import { ArrowRight, BookOpen, CircleGauge, Compass, Feather, Flag, Footprints, Leaf, MapPin, Shell, Sparkles, Star, Telescope, UserRoundCheck, type LucideIcon } from "lucide-react";
import { AvatarId, useGame } from "@/contexts/GameContext";

type AvatarCard = { id: AvatarId; label: string; note: string; gender: "Nam" | "Nữ"; icon: LucideIcon; tint: string; image?: string };
const iconSet = [Compass, MapPin, Telescope, Feather, Flag, Leaf, CircleGauge, Star, Shell, Footprints];
const tones = ["bg-[#fff0b6]", "bg-[#dceef6]", "bg-[#f5dfd2]", "bg-[#e7f2e5]", "bg-[#ece3f5]", "bg-[#f9e4c8]", "bg-[#dfe9d5]", "bg-[#e1eaf8]", "bg-[#f5e3e4]", "bg-[#e3f0ed]"];
const notes = ["thích tìm quy luật", "đọc dấu bản đồ", "soi từng chi tiết", "ghi lời giải rõ ràng", "dẫn đường vững vàng", "chăm từng bước nhỏ", "đo đạc chính xác", "luôn tò mò khám phá", "giữ nhịp bình tĩnh", "không bỏ sót manh mối"];
const boys = ["Minh La Bàn", "Tí Đỉnh Đồi", "Nam Kính Lúp", "Bảo Lông Vũ", "Khoa Cờ Mốc", "Sơn Rêu Xanh", "Huy Kim Chỉ", "Dũng Sao Băng", "Lâm Vỏ Sò", "Phúc Dấu Chân"];
const girls = ["An Mây Nhỏ", "Linh Bản Đồ", "Vy Kính Lúp", "Mai Lông Vũ", "Nhi Cờ Mốc", "Hà Rêu Xanh", "Thư Kim Chỉ", "Lan Sao Băng", "Yến Vỏ Sò", "Chi Dấu Chân"];
const avatarImages: Record<AvatarId, string> = {
  b01: "/manus-storage/math4fun-avatar-b01_6f565763.png", b02: "/manus-storage/math4fun-avatar-b02_94a2f9b6.png", b03: "/manus-storage/math4fun-avatar-b03_de75ed1e.png", b04: "/manus-storage/math4fun-avatar-b04_89e025bd.png", b05: "/manus-storage/math4fun-avatar-b05_f12579a9.png",
  b06: "/manus-storage/math4fun-avatar-b06_6d7df86d.png", b07: "/manus-storage/math4fun-avatar-b07_378f921a.png", b08: "/manus-storage/math4fun-avatar-b08_20f38f4b.png", b09: "/manus-storage/math4fun-avatar-b09_f0041bd7.png", b10: "/manus-storage/math4fun-avatar-b10_37db42f1.png",
  g01: "/manus-storage/math4fun-avatar-g01_0c3aa29a.png", g02: "/manus-storage/math4fun-avatar-g02_4dfa425d.png", g03: "/manus-storage/math4fun-avatar-g03_efd04fca.png", g04: "/manus-storage/math4fun-avatar-g04_b6eb05c9.png", g05: "/manus-storage/math4fun-avatar-g05_e99e6afc.png",
  g06: "/manus-storage/math4fun-avatar-g06_310e75f1.png", g07: "/manus-storage/math4fun-avatar-g07_000ffec0.png", g08: "/manus-storage/math4fun-avatar-g08_37fd713b.png", g09: "/manus-storage/math4fun-avatar-g09_c50a1331.png", g10: "/manus-storage/math4fun-avatar-g10_262e51c0.png",
  compass: "/manus-storage/math4fun-avatar-compass_c1cebf77.png", ember: "/manus-storage/math4fun-avatar-ember_095098ee.png", tide: "/manus-storage/math4fun-avatar-tide_cc836336.png", leaf: "/manus-storage/math4fun-avatar-leaf_b35efd62.png",
};
const avatars: AvatarCard[] = [
  ...boys.map((label, index) => { const id = `b${String(index + 1).padStart(2, "0")}` as AvatarId; return { id, label, note: notes[index], gender: "Nam" as const, icon: iconSet[index], tint: tones[index], image: avatarImages[id] }; }),
  ...girls.map((label, index) => { const id = `g${String(index + 1).padStart(2, "0")}` as AvatarId; return { id, label, note: notes[(index + 3) % notes.length], gender: "Nữ" as const, icon: iconSet[(index + 2) % iconSet.length], tint: tones[(index + 4) % tones.length], image: avatarImages[id] }; }),
];
const legacyAvatars: AvatarCard[] = [
  { id: "compass", label: "Mây La Bàn", note: "ham khám phá", gender: "Nữ", icon: Compass, tint: "bg-[#fff0b6]", image: "/manus-storage/math4fun-avatar-compass_c1cebf77.png" },
  { id: "ember", label: "Nhi Hỏa Tinh", note: "gan dạ thử thách", gender: "Nữ", icon: Sparkles, tint: "bg-[#ffe4dc]", image: "/manus-storage/math4fun-avatar-ember_095098ee.png" },
  { id: "tide", label: "Lam Thủy Triều", note: "điềm tĩnh suy luận", gender: "Nữ", icon: Shell, tint: "bg-[#e4f3fb]", image: "/manus-storage/math4fun-avatar-tide_cc836336.png" },
  { id: "leaf", label: "Mầm Rêu Non", note: "chăm chỉ từng bước", gender: "Nữ", icon: Leaf, tint: "bg-[#e7f2e5]", image: "/manus-storage/math4fun-avatar-leaf_b35efd62.png" },
];
const getAvatar = (id: AvatarId) => avatars.find((entry) => entry.id === id) ?? legacyAvatars.find((entry) => entry.id === id) ?? avatars[0];

function AvatarGlyph({ avatar, small = false }: { avatar: AvatarCard; small?: boolean }) {
  const Icon = avatar.icon;
  if (avatar.image) return <img src={avatar.image} alt="" className={small ? "h-12 w-12 object-contain" : "h-24 w-full object-contain"} />;
  return <span className={`${small ? "h-12 w-12" : "mx-auto h-24 w-24"} grid place-items-center border-2 border-[#172a48] bg-[#fffdf6] text-[#172a48] shadow-[3px_3px_0_#172a48]`}><Icon size={small ? 21 : 42} strokeWidth={1.7}/></span>;
}

export default function StartPage() {
  const [, navigate] = useLocation();
  const { createProfile, profiles, signIn, setLegacyProfilePassword } = useGame();
  const [name, setName] = useState(""); const [username, setUsername] = useState(""); const [password, setPassword] = useState("");
  const [avatar, setAvatar] = useState<AvatarId>("b01"); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [chosenId, setChosenId] = useState<string | null>(null);
  const selected = getAvatar(avatar); const chosen = profiles.find((entry) => entry.id === chosenId) ?? null;
  async function register(event: FormEvent) { event.preventDefault(); setBusy(true); setNotice(""); const result = await createProfile(name, avatar, username, password); setBusy(false); setNotice(result.message); if (result.ok) navigate("/"); }
  async function login() { if (!chosen) return; setBusy(true); setNotice(""); const result = chosen.passwordHash ? await signIn(chosen.id, password) : await setLegacyProfilePassword(chosen.id, username, password); setBusy(false); setNotice(result.message); if (result.ok) navigate("/"); }
  return <section className="mx-auto max-w-6xl overflow-hidden border-2 border-[#172a48] bg-[#fffdf6] shadow-[7px_7px_0_#172a48]">
    <div className="relative grid gap-8 p-6 sm:p-9 lg:grid-cols-[.8fr_1.2fr]"><div className="paper-noise pointer-events-none absolute inset-0 opacity-40"/>
      <aside className="relative border-b-2 border-dashed border-[#d7d0bf] pb-7 lg:border-b-0 lg:border-r-2 lg:pb-0 lg:pr-8"><span className="field-tag"><BookOpen size={14}/> HỒ SƠ LOCAL</span><h1 className="mt-5 font-display text-5xl font-black leading-[.92] tracking-tight">Chọn bạn<br/>đồng hành.</h1><p className="mt-5 text-sm leading-relaxed text-[#476275]">Mỗi học sinh có một nhật ký riêng, nhận ra bằng tên đăng nhập và mật khẩu trên thiết bị này.</p><div className="relative mt-6 overflow-hidden border-2 border-[#172a48] bg-[#172a48] p-4 text-white shadow-[4px_4px_0_#f6b73c]"><div className="absolute -right-2 -top-4 opacity-35"><AvatarGlyph avatar={selected}/></div><div className="relative"><p className="font-mono text-[10px] font-black tracking-[.16em] text-[#f6b73c]">THẺ ĐANG CHỌN</p><b className="mt-3 block font-display text-2xl">{selected.label}</b><p className="mt-1 text-sm text-[#d5dfed]">{selected.gender} · {selected.note}</p></div></div><Link href="/" className="relative mt-6 inline-flex items-center gap-2 text-sm font-black text-[#172a48] underline decoration-[#f6b73c] decoration-2 underline-offset-4">Về hành trình <ArrowRight size={15}/></Link></aside>
      <form onSubmit={register} className="relative"><p className="section-kicker">PHIẾU ĐĂNG KÝ NHÀ THÁM HIỂM</p><label className="mt-4 block font-display text-2xl font-black">Em muốn được gọi là gì?</label><input value={name} onChange={(event) => setName(event.target.value)} maxLength={22} placeholder="Ví dụ: Violet" className="mt-3 w-full border-2 border-[#172a48] bg-white px-4 py-3 font-display text-xl font-black outline-none focus:bg-[#fff8da]"/><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Tên đăng nhập<input value={username} onChange={(event) => setUsername(event.target.value)} maxLength={18} autoComplete="username" placeholder="violet.math" className="mt-1 block w-full border-2 border-[#172a48] bg-white px-3 py-2 outline-none focus:bg-[#fff8da]"/></label><label className="text-sm font-bold">Mật khẩu<input value={password} onChange={(event) => setPassword(event.target.value)} minLength={6} maxLength={64} autoComplete="new-password" type="password" placeholder="Ít nhất 6 ký tự" className="mt-1 block w-full border-2 border-[#172a48] bg-white px-3 py-2 outline-none focus:bg-[#fff8da]"/></label></div>
        <div className="mt-6 flex items-end justify-between gap-3"><div><p className="font-display text-2xl font-black">20 bạn đồng hành</p><p className="mt-1 text-sm text-[#58708b]">10 thẻ Nam · 10 thẻ Nữ. Mỗi thẻ là một tiêu bản dã ngoại riêng.</p></div><Compass className="text-[#f6b73c]" size={28}/></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-5">{avatars.map((entry, index) => <button type="button" key={entry.id} onClick={() => setAvatar(entry.id)} className={`relative overflow-hidden border-2 border-[#172a48] p-2 text-left shadow-[2px_2px_0_#172a48] transition ${index % 2 ? "rotate-[.25deg]" : "-rotate-[.25deg]"} ${avatar === entry.id ? "-translate-y-1 bg-[#172a48] text-white shadow-[4px_4px_0_#f6b73c]" : `${entry.tint} hover:-translate-y-0.5`}`}><span className={`absolute left-1 top-1 border border-[#172a48] px-1 font-mono text-[8px] font-black tracking-[.1em] ${avatar === entry.id ? "bg-[#f6b73c] text-[#172a48]" : "bg-white/80 text-[#476275]"}`}>SPECIMEN {entry.id.toUpperCase()}</span><div className="pt-3"><AvatarGlyph avatar={entry}/></div><b className="mt-1 block border-t border-dashed border-current pt-1 text-xs leading-tight">{entry.label}</b><small className={avatar === entry.id ? "block text-[10px] text-[#d5dfed]" : "block text-[10px] text-[#58708b]"}>{entry.gender} · {entry.note}</small><span className="mt-1 block font-mono text-[8px] font-bold tracking-[.12em] opacity-70">M4F · FIELD TAG</span>{avatar === entry.id && <span className="absolute right-1 top-1 grid h-5 w-5 place-items-center rounded-full bg-[#f6b73c] text-[#172a48]"><Sparkles size={12}/></span>}</button>)}</div>{notice && <p className="mt-4 border-l-4 border-[#f6b73c] bg-[#fff8da] px-3 py-2 text-sm font-bold">{notice}</p>}<button disabled={busy} className="mt-7 inline-flex items-center gap-2 border-2 border-[#172a48] bg-[#f6b73c] px-5 py-3 font-bold shadow-[3px_3px_0_#172a48] transition active:scale-[.97] disabled:opacity-60"><Sparkles size={17}/>{busy ? "Đang ghi nhật ký…" : `Vào hành trình với ${selected.label}`}</button></form>
    </div>
    {profiles.length > 0 && <section className="relative border-t-2 border-[#172a48] bg-[#172a48] p-5 text-white"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-[#f6b73c]">NHẬT KÝ ĐÃ CÓ TRÊN MÁY NÀY</p><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{profiles.map((entry) => { const avatarInfo = getAvatar(entry.avatar); return <button key={entry.id} onClick={() => { setChosenId(entry.id); setPassword(""); setUsername(entry.username ?? ""); setNotice(""); }} className={`flex items-center gap-3 border p-3 text-left transition ${chosenId === entry.id ? "border-[#f6b73c] bg-white/25" : "border-white/35 bg-white/10 hover:bg-white/20"}`}><AvatarGlyph avatar={avatarInfo} small/><span><b className="block">{entry.name}</b><small className="text-[#d5dfed]">{entry.username ? `@${entry.username}` : "Cần đặt mật khẩu"} · {entry.gold ?? 0} Gold</small></span><UserRoundCheck className="ml-auto text-[#f6b73c]" size={18}/></button>; })}</div>{chosen && <div className="mt-4 grid gap-3 border border-dashed border-[#f6b73c] bg-white/10 p-4 sm:grid-cols-[1fr_1fr_auto]"><label className="text-sm font-bold">{chosen.passwordHash ? "Nhật ký" : "Tên đăng nhập lần đầu"}<input value={username} onChange={(event) => setUsername(event.target.value)} disabled={Boolean(chosen.passwordHash)} maxLength={18} className="mt-1 block w-full border border-white/50 bg-[#fffdf6] px-3 py-2 text-sm text-[#172a48] outline-none disabled:opacity-70"/></label><label className="text-sm font-bold">{chosen.passwordHash ? "Mật khẩu" : "Đặt mật khẩu"}<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" minLength={6} autoComplete={chosen.passwordHash ? "current-password" : "new-password"} className="mt-1 block w-full border border-white/50 bg-[#fffdf6] px-3 py-2 text-sm text-[#172a48] outline-none"/></label><button type="button" onClick={login} disabled={busy} className="self-end border-2 border-[#f6b73c] bg-[#f6b73c] px-4 py-2 text-sm font-black text-[#172a48] shadow-[2px_2px_0_white] disabled:opacity-60">{chosen.passwordHash ? "Đăng nhập" : "Bảo vệ & vào game"}</button></div>}</section>}
    <p className="relative border-t-2 border-dashed border-[#d7d0bf] p-4 text-center text-xs text-[#58708b]">Prototype local: tài khoản và bảng xếp hạng chỉ so sánh các nhật ký trên trình duyệt này.</p>
  </section>;
}
