/**
 * Field Journal Quest — Stats dossier: parchment evidence, indigo ink, marigold controls and route-bound rewards.
 */
import { useRef, useState } from "react";
import { Link } from "wouter";
import { BadgeCheck, BarChart3, BookOpen, Coins, Crosshair, Download, Flame, KeyRound, LockKeyhole, PackageOpen, ScrollText, ShieldCheck, Sparkles, Swords, Upload } from "lucide-react";
import { ELEMENT_ORDER, ELEMENT_XP_PER_LEVEL, GUARDIANS, MAGIC_MEDIA, SHOP_ITEMS, STATIONS, type ElementName } from "@/game/gameData";
import { useGame } from "@/contexts/GameContext";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";

const ELEMENT_COLORS: Record<ElementName, string> = { "sấm": "#f6b73c", "lửa": "#ee6b4e", "nước": "#55a9dd", "độc": "#8e69ad", "gió": "#3e9b7a", "đất": "#b17a3d" };
const ELEMENT_SIGILS: Record<ElementName, string> = { "sấm": "ϟ", "lửa": "✦", "nước": "≈", "độc": "☾", "gió": "≋", "đất": "◆" };
type PinMode = "restore" | "setup" | "change" | "reset";

export default function StatsPage() {
  const { profile, stationProgress, siteVisitCount, lastSiteVisitAt, mostUsedMagicElement, magicBookWatchedCount, hasMagicBookAchievement, elementXp, elementLevel, weeklyMagicQuest, createProfileBackup, restoreProfileBackup, hasParentPin, parentSecurityQuestion, setParentPin, changeParentPin, resetParentPin, gold, goldHistory, inventory, elementBadges, learningBadges } = useGame();
  const uploadRef = useRef<HTMLInputElement>(null);
  const [transferMessage, setTransferMessage] = useState("");
  const [pendingBackup, setPendingBackup] = useState<File | null>(null);
  const [pinMode, setPinMode] = useState<PinMode>("setup");
  const [pinDialogOpen, setPinDialogOpen] = useState(false);
  const [pinBusy, setPinBusy] = useState(false);
  const [currentPin, setCurrentPin] = useState("");
  const [nextPin, setNextPin] = useState("");
  const [confirmPin, setConfirmPin] = useState("");
  const [securityQuestion, setSecurityQuestion] = useState("");
  const [securityAnswer, setSecurityAnswer] = useState("");
  const [goldFilter, setGoldFilter] = useState<"all" | "income" | "expense">("all");

  const resetPinFields = () => { setCurrentPin(""); setNextPin(""); setConfirmPin(""); setSecurityQuestion(""); setSecurityAnswer(""); };
  const openPin = (mode: PinMode) => { resetPinFields(); setPinMode(mode); setPinDialogOpen(true); };
  const downloadBackup = () => {
    const json = createProfileBackup(); if (!json || !profile) return;
    const url = URL.createObjectURL(new Blob([json], { type: "application/json" }));
    const link = document.createElement("a"); link.href = url; link.download = `math4fun-${profile.name.trim().replace(/\s+/g, "-").toLowerCase() || "ho-so"}-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url);
    setTransferMessage("Đã tạo tệp sao lưu JSON cho hồ sơ hiện tại.");
  };
  const beginRestore = (file?: File) => { if (!file) return; setPendingBackup(file); openPin(hasParentPin ? "restore" : "setup"); };
  const submitPin = async () => {
    const requiresNewPin = pinMode === "setup" || pinMode === "change" || pinMode === "reset";
    if (requiresNewPin && nextPin !== confirmPin) { setTransferMessage("Hai lần nhập PIN mới chưa khớp."); return; }
    setPinBusy(true);
    try {
      let result: { ok: boolean; message: string };
      if (pinMode === "setup") result = await setParentPin(nextPin, securityQuestion, securityAnswer);
      else if (pinMode === "change") result = await changeParentPin(currentPin, nextPin, securityQuestion, securityAnswer);
      else if (pinMode === "reset") result = await resetParentPin(securityAnswer, nextPin);
      else result = pendingBackup ? await restoreProfileBackup(await pendingBackup.text(), currentPin) : { ok: false, message: "Chưa chọn tệp JSON để khôi phục." };
      setTransferMessage(result.message);
      if (!result.ok) return;
      if (pinMode === "setup" && pendingBackup) {
        const restored = await restoreProfileBackup(await pendingBackup.text(), nextPin);
        setTransferMessage(restored.message);
        if (!restored.ok) return;
      }
      setPinDialogOpen(false);
    } finally { setPinBusy(false); }
  };

  if (!profile) { const pendingGuardian = GUARDIANS.find((guardian) => guardian.id === "atlas"); return <section className="stats-blank-dossier"><header className="grid gap-5 lg:grid-cols-[1fr_230px]"><div><p className="section-kicker">HỒ SƠ DÃ NGOẠI · CHỜ KÝ TÊN</p><h1 className="font-display text-4xl font-black">Báo cáo bằng chứng chưa niêm phong</h1><p>Nhật ký đang chờ chủ nhân. Khi lập hồ sơ, mọi câu toán, Gold và dấu ấn sẽ được ghi theo một tuyến riêng.</p></div><aside className="rotate-[-2deg] border-2 border-[#172a48] bg-[#e8f0e4] p-3 shadow-[3px_3px_0_#172a48]"><span className="field-tag">SPECIMEN 06 · LOCKED</span><div className="mx-auto mt-2 grid h-28 w-28 place-items-center rounded-full border-2 border-dashed border-[#172a48] bg-[#fffdf6]"><img src={pendingGuardian?.sprite} alt="Tiêu bản Atlas niêm phong" className="h-20 w-20 object-contain grayscale-[.6]"/></div><p className="mt-2 border-t border-dashed border-[#9ea99e] pt-2 font-mono text-[9px] font-bold tracking-[.12em] text-[#58708b]">ATLAS · BẢO HỘ · CHỜ 20 BẰNG CHỨNG</p></aside></header><div className="stats-blank-route"><span className="is-active">01<br/><small>Ký tên</small></span><i /><span>02<br/><small>Thu thập</small></span><i /><span>03<br/><small>Rèn ấn</small></span><i /><span>04<br/><small>Đấu Boss</small></span></div><div className="stats-blank-evidence"><article><p className="section-kicker">DẤU VẾT TRÌNH DUYỆT</p><b>Đã mở {siteVisitCount} lượt</b><small>{lastSiteVisitAt ? `Lần gần nhất ${new Date(lastSiteVisitAt).toLocaleString("vi-VN")}` : "Chưa có lượt ghé thăm"}</small></article><article className="stats-blank-seal"><ShieldCheck size={27}/><b>Kho đồ chờ mở</b><small>thu thập Gold bằng những lời giải đúng</small></article><article className="border-2 border-dashed border-[#172a48] bg-[#fff8da] p-4"><p className="section-kicker">MỐC BẰNG CHỨNG</p><b>20 lời giải đúng</b><small>mở niêm phong Atlas và báo cáo Boss</small></article></div><Link href="/start" className="stats-blank-cta">Ký tên mở tuyến bằng chứng</Link></section>; }

  const accuracy = profile.metrics.totalAnswers ? Math.round((profile.metrics.correctAnswers / profile.metrics.totalAnswers) * 100) : 0;
  const readyStations = STATIONS.filter((station) => station.status === "ready");
  const questProgress = weeklyMagicQuest ? Math.round((weeklyMagicQuest.usedCount / weeklyMagicQuest.target) * 100) : 0;
  const cards = [
    { label: "Gold hiện có", value: gold, icon: Coins, tone: "bg-[#fff0b6]" }, { label: "Đáp án đã làm", value: profile.metrics.totalAnswers, icon: BookOpen, tone: "bg-[#eaf0f7]" },
    { label: "Độ chính xác", value: `${accuracy}%`, icon: Crosshair, tone: "bg-[#e7f2e5]" }, { label: "Chuỗi học", value: `${profile.streak} ngày`, icon: Flame, tone: "bg-[#ffe4dc]" },
    { label: "Boss thắng", value: profile.metrics.bossWins, icon: Swords, tone: "bg-[#f0e7f6]" }, { label: "Phép dùng nhiều nhất", value: mostUsedMagicElement ? MAGIC_MEDIA[mostUsedMagicElement].shortLabel : "Chưa có", icon: Sparkles, tone: "bg-[#fff0b6]" },
  ];
  const title: Record<PinMode, string> = { setup: "Tạo PIN phụ huynh", restore: "Xác nhận PIN phụ huynh", change: "Đổi PIN phụ huynh", reset: "Đặt lại PIN bằng câu hỏi bảo mật" };
  const needsQuestion = pinMode === "setup" || pinMode === "change";
  const needsNewPin = pinMode !== "restore";
  const goldIncome = goldHistory.filter((entry) => entry.amount > 0).reduce((sum, entry) => sum + entry.amount, 0);
  const goldExpense = Math.abs(goldHistory.filter((entry) => entry.amount < 0).reduce((sum, entry) => sum + entry.amount, 0));
  const visibleGoldHistory = goldHistory.filter((entry) => goldFilter === "all" || (goldFilter === "income" ? entry.amount > 0 : entry.amount < 0));

  return <section>
    <header className="mb-6"><p className="section-kicker">BẰNG CHỨNG HÀNH TRÌNH · LOCAL ONLY</p><h1 className="font-display text-4xl font-black">Thống kê của {profile.name}</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-[#58708b]">Nhật ký này lưu trên trình duyệt đang dùng; Gold, kho đồ và huy hiệu không có giá trị thương mại.</p><div className="mt-4 flex flex-wrap items-center gap-2 border-y-2 border-dashed border-[#c9b88c] bg-[#fff8da] px-3 py-2 font-mono text-[10px] font-bold tracking-[.13em] text-[#476275]"><span className="border border-[#172a48] bg-[#f6b73c] px-2 py-1">CÂU TOÁN</span><i className="w-7 border-t-2 border-dotted border-[#172a48]"/><span className="border border-[#172a48] bg-white px-2 py-1">BẰNG CHỨNG</span><i className="w-7 border-t-2 border-dotted border-[#172a48]"/><span className="border border-[#172a48] bg-[#e8f0e4] px-2 py-1">ẤN & HUY HIỆU</span><i className="w-7 border-t-2 border-dotted border-[#172a48]"/><span className="border border-[#172a48] bg-white px-2 py-1">ATLAS</span></div></header>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(({ label, value, icon: Icon, tone }) => <article key={label} className={`evidence-card border-2 border-[#172a48] p-4 shadow-[3px_3px_0_#172a48] ${tone}`}><Icon size={18}/><p className="mt-5 font-display text-4xl font-black">{value}</p><p className="mt-1 text-sm font-bold text-[#476275]">{label}</p></article>)}</div>
    <section className="mt-6 border-2 border-[#172a48] bg-[#fff8da] p-5 shadow-[5px_5px_0_#172a48]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-kicker"><Coins size={13}/> SỔ GIAO DỊCH · GOLD</p><h2 className="mt-1 font-display text-3xl font-black">Dấu vết Gold đã dùng</h2><p className="mt-1 text-sm text-[#58708b]">Ghi rõ khoản thưởng, phí mở chủ đề, gợi ý và mua đồ trên nhật ký cục bộ này.</p></div><div className="flex gap-2 text-center"><span className="border-2 border-[#172a48] bg-[#e7f2e5] px-3 py-2 text-xs font-bold">THU<br/><b className="text-base text-[#235b45]">+{goldIncome}</b></span><span className="border-2 border-[#172a48] bg-[#ffe4dc] px-3 py-2 text-xs font-bold">CHI<br/><b className="text-base text-[#9e3d2d]">−{goldExpense}</b></span></div></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-y-2 border-dashed border-[#c9b88c] py-2"><p className="font-mono text-[10px] font-black tracking-[.13em] text-[#58708b]">{goldHistory.length} GIAO DỊCH ĐƯỢC LƯU</p><select value={goldFilter} onChange={(event) => setGoldFilter(event.target.value as typeof goldFilter)} className="border-2 border-[#172a48] bg-white px-3 py-1.5 text-xs font-bold outline-none"><option value="all">Mọi giao dịch</option><option value="expense">Khoản chi</option><option value="income">Khoản thu</option></select></div><ol className="mt-3 max-h-56 space-y-2 overflow-y-auto pr-1">{visibleGoldHistory.length ? visibleGoldHistory.map((entry) => <li key={entry.id} className="flex items-center justify-between gap-3 border-l-4 border-[#172a48] bg-[#fffdf6] px-3 py-2 text-sm"><div><b>{entry.label}</b><small className="mt-0.5 block text-[10px] text-[#58708b]">{new Date(entry.createdAt).toLocaleString("vi-VN")} · {entry.category}</small></div><strong className={entry.amount >= 0 ? "text-[#235b45]" : "text-[#9e3d2d]"}>{entry.amount >= 0 ? "+" : ""}{entry.amount} Gold</strong></li>) : <li className="border-2 border-dashed border-[#c9b88c] bg-[#fffdf6] p-3 text-sm text-[#58708b]">Chưa có khoản Gold thuộc bộ lọc này.</li>}</ol></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]"><article className="paper-stack border-2 border-[#172a48] bg-[#fffdf6] p-5 shadow-[5px_5px_0_#172a48]"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="section-kicker">BẢNG LUYỆN ẤN</p><h2 className="font-display text-3xl font-black">XP và huy hiệu nguyên tố</h2><p className="mt-1 text-sm text-[#58708b]">Đạt <strong>bậc 3</strong> của một hệ để nhận Huy hiệu Ba Bậc trên hồ sơ.</p></div><span className="field-tag"><BadgeCheck size={13}/> {elementBadges.length}/6 HUY HIỆU</span></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{ELEMENT_ORDER.map((element) => { const xp = elementXp[element] ?? 0; const progress = xp % ELEMENT_XP_PER_LEVEL; const earned = elementBadges.includes(element); return <article key={element} className="relative border border-[#172a48] bg-[#f7f0df] p-3"><div className="flex items-center justify-between"><span className="text-2xl" style={{color: ELEMENT_COLORS[element]}}>{ELEMENT_SIGILS[element]}</span><div className="text-right"><b className="text-sm">{MAGIC_MEDIA[element].shortLabel}</b><small className="block text-xs text-[#58708b]">Bậc {elementLevel(element)}</small></div></div><div className="mt-3 h-2.5 overflow-hidden border border-[#172a48] bg-[#fffdf6]"><div className="h-full" style={{width: `${progress / ELEMENT_XP_PER_LEVEL * 100}%`, backgroundColor: ELEMENT_COLORS[element]}}/></div><p className="mt-1 text-xs font-bold text-[#476275]">{xp} XP · {earned ? "Đã nhận Huy hiệu Ba Bậc" : `${Math.max(0, 200 - xp)} XP đến huy hiệu`}</p>{earned && <span className="absolute -right-2 -top-2 grid h-8 w-8 place-items-center rounded-full border-2 border-[#172a48] bg-[#f6b73c] shadow-[2px_2px_0_#172a48]" aria-label={`Huy hiệu ${element}`}>★</span>}</article>; })}</div></article>
      <aside className="space-y-5"><article className="border-2 border-[#172a48] bg-[#172a48] p-5 text-white shadow-[4px_4px_0_#f6b73c]"><ScrollText className="text-[#f6b73c]"/><p className="mt-3 text-xs font-bold tracking-[.15em] text-[#f6b73c]">NHIỆM VỤ TUẦN</p>{weeklyMagicQuest && <><h2 className="mt-2 font-display text-2xl font-black">{weeklyMagicQuest.title}</h2><p className="mt-2 text-sm text-[#d5dfed]">{weeklyMagicQuest.note}</p><b className="mt-4 block">{weeklyMagicQuest.usedCount}/{weeklyMagicQuest.target} lần</b><div className="mt-2 h-3 border border-white/60 bg-white/10"><div className="h-full bg-[#f6b73c]" style={{width: `${questProgress}%`}}/></div><small className="mt-3 block font-bold text-[#f6b73c]">{weeklyMagicQuest.rewardClaimed ? `Đã nhận +${weeklyMagicQuest.rewardXp} XP` : `Hoàn thành để nhận +${weeklyMagicQuest.rewardXp} XP`}</small></>}</article><article className="border-2 border-[#172a48] bg-[#fff0b6] p-4 shadow-[3px_3px_0_#172a48]"><Flame className="text-[#d85b41]"/><p className="mt-3 section-kicker">HUY HIỆU BỀN BỈ</p><h3 className="font-display text-2xl font-black">Chuỗi học liên tục</h3><p className="mt-1 text-xs text-[#476275]">Học vào ngày kế tiếp để duy trì dấu mốc; gián đoạn sẽ khởi động lại chuỗi.</p><div className="mt-3 grid grid-cols-2 gap-2 text-center text-xs font-bold"><span className={`border-2 border-[#172a48] p-2 ${learningBadges.includes("streak-7") ? "bg-[#172a48] text-[#fff0b6]" : "bg-white text-[#58708b]"}`}>7 NGÀY<br/><b>{learningBadges.includes("streak-7") ? "ĐÃ NHẬN" : `${Math.max(0, 7 - profile.streak)} ngày nữa`}</b></span><span className={`border-2 border-[#172a48] p-2 ${learningBadges.includes("streak-14") ? "bg-[#172a48] text-[#fff0b6]" : "bg-white text-[#58708b]"}`}>14 NGÀY<br/><b>{learningBadges.includes("streak-14") ? "ĐÃ NHẬN" : `${Math.max(0, 14 - profile.streak)} ngày nữa`}</b></span></div></article><article className="evidence-card border-2 border-[#172a48] bg-[#e8f0e4] p-4"><PackageOpen/><p className="mt-3 section-kicker">KHO ĐỒ HIỆN CÓ</p>{SHOP_ITEMS.map((item) => <div key={item.id} className="mt-2 flex justify-between border-t border-dashed border-[#9ea99e] pt-2 text-sm"><span>{item.label.replace("Bình Lộ Sáng ", "Bình ")}</span><b>× {inventory[item.id]}</b></div>)}</article></aside></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_300px]"><article className="paper-stack border-2 border-[#172a48] bg-[#fffdf6] p-5 shadow-[5px_5px_0_#172a48]"><BarChart3 size={18}/><h2 className="mt-2 font-display text-3xl font-black">Dấu vết trạm đã mở</h2><div className="mt-5 space-y-4">{readyStations.map((station) => { const item = stationProgress(station.id); return <div key={station.id}><div className="flex justify-between gap-3 text-sm font-bold"><span>{station.code} · {station.title}</span><span>{item.correct}/{item.target}</span></div><div className="mt-2 h-3 border border-[#172a48] bg-[#f5efdf]"><div className={`h-full ${station.accent}`} style={{width: `${Math.min(100, item.correct / item.target * 100)}%`}}/></div></div>; })}</div></article><aside className="border-2 border-[#172a48] bg-[#172a48] p-5 text-white shadow-[4px_4px_0_#f6b73c]"><ShieldCheck className="text-[#f6b73c]"/><h2 className="mt-4 font-display text-3xl font-black">{profile.completedStationIds.length}/20 dấu niêm phong</h2><p className="mt-2 text-sm text-[#d5dfed]">{hasMagicBookAchievement ? "Đã mở huy hiệu Nhà Lưu Trữ Sáu Ấn." : `Đã xem ${magicBookWatchedCount}/6 hoạt ảnh nguyên tố.`}</p></aside></section>
    <section className="mt-6 border-2 border-[#172a48] bg-[#e8f0e4] p-5 shadow-[5px_5px_0_#172a48]"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-center"><div><p className="section-kicker">CHUYỂN HỒ SƠ · JSON</p><h2 className="font-display text-3xl font-black">Sao lưu và quản lý PIN</h2><p className="mt-1 max-w-2xl text-sm leading-relaxed text-[#476275]">Khôi phục thêm một hồ sơ mới, không ghi đè nhật ký hiện tại. PIN và câu trả lời bảo mật chỉ lưu dạng mã hóa một chiều trong trình duyệt.</p>{transferMessage && <p className="mt-3 text-sm font-bold text-[#244e4a]" role="status">{transferMessage}</p>}</div><div className="flex flex-wrap gap-3"><button onClick={downloadBackup} className="border-2 border-[#172a48] bg-white px-4 py-3 text-sm font-black shadow-[3px_3px_0_#172a48]"><Download className="mr-2 inline" size={16}/>Sao lưu</button><button onClick={() => openPin(hasParentPin ? "change" : "setup")} className="border-2 border-[#172a48] bg-[#d5dfed] px-4 py-3 text-sm font-black shadow-[3px_3px_0_#172a48]"><KeyRound className="mr-2 inline" size={16}/>{hasParentPin ? "Đổi PIN" : "Tạo PIN"}</button>{hasParentPin && <button onClick={() => openPin("reset")} className="border-2 border-[#172a48] bg-white px-4 py-3 text-sm font-black shadow-[3px_3px_0_#172a48]"><LockKeyhole className="mr-2 inline" size={16}/>Quên PIN</button>}<button onClick={() => uploadRef.current?.click()} className="border-2 border-[#172a48] bg-[#f6b73c] px-4 py-3 text-sm font-black shadow-[3px_3px_0_#172a48]"><Upload className="mr-2 inline" size={16}/>Khôi phục JSON</button><input ref={uploadRef} type="file" accept="application/json,.json" className="sr-only" onChange={(event) => { beginRestore(event.target.files?.[0]); event.target.value = ""; }}/></div></div></section>
    <Dialog open={pinDialogOpen} onOpenChange={setPinDialogOpen}><DialogContent className="border-2 border-[#172a48] bg-[#fffdf6] text-[#172a48] shadow-[6px_6px_0_#172a48]"><DialogHeader><p className="section-kicker">PHỤ HUYNH · NIÊM PHONG LOCAL</p><DialogTitle className="font-display text-3xl font-black">{title[pinMode]}</DialogTitle><DialogDescription className="text-[#476275]">{pinMode === "reset" ? `Trả lời câu hỏi đã lưu: “${parentSecurityQuestion ?? "Không có câu hỏi"}”.` : "Dữ liệu bí mật không được gửi ra ngoài trình duyệt này."}</DialogDescription></DialogHeader><div className="space-y-3">{pinMode === "restore" || pinMode === "change" ? <label className="block text-sm font-bold">PIN hiện tại<input autoFocus inputMode="numeric" type="password" value={currentPin} onChange={(e) => setCurrentPin(e.target.value.replace(/\D/g, "").slice(0, 8))} className="mt-1 block w-full border-2 border-[#172a48] bg-white px-3 py-2 font-mono tracking-[.3em]"/></label> : null}{needsQuestion && <><label className="block text-sm font-bold">Câu hỏi bảo mật<input value={securityQuestion} onChange={(e) => setSecurityQuestion(e.target.value)} placeholder="Ví dụ: Món ăn gia đình yêu thích?" className="mt-1 block w-full border-2 border-[#172a48] bg-white px-3 py-2"/></label><label className="block text-sm font-bold">Câu trả lời bảo mật<input type="password" value={securityAnswer} onChange={(e) => setSecurityAnswer(e.target.value)} className="mt-1 block w-full border-2 border-[#172a48] bg-white px-3 py-2"/></label></>}{pinMode === "reset" && <label className="block text-sm font-bold">Câu trả lời bảo mật<input autoFocus type="password" value={securityAnswer} onChange={(e) => setSecurityAnswer(e.target.value)} className="mt-1 block w-full border-2 border-[#172a48] bg-white px-3 py-2"/></label>}{needsNewPin && <><label className="block text-sm font-bold">PIN mới<input inputMode="numeric" type="password" value={nextPin} onChange={(e) => setNextPin(e.target.value.replace(/\D/g, "").slice(0, 8))} className="mt-1 block w-full border-2 border-[#172a48] bg-white px-3 py-2 font-mono tracking-[.3em]"/></label><label className="block text-sm font-bold">Nhập lại PIN mới<input inputMode="numeric" type="password" value={confirmPin} onChange={(e) => setConfirmPin(e.target.value.replace(/\D/g, "").slice(0, 8))} className="mt-1 block w-full border-2 border-[#172a48] bg-white px-3 py-2 font-mono tracking-[.3em]"/></label></>}</div><DialogFooter><button onClick={() => setPinDialogOpen(false)} className="border-2 border-[#172a48] bg-white px-4 py-2 font-black">Hủy</button><button onClick={() => void submitPin()} disabled={pinBusy} className="border-2 border-[#172a48] bg-[#f6b73c] px-4 py-2 font-black shadow-[2px_2px_0_#172a48] disabled:opacity-50">{pinBusy ? "Đang kiểm tra…" : "Xác nhận"}</button></DialogFooter></DialogContent></Dialog>
  </section>;
}
