/** Field Journal Quest — local evidence is framed as a parent-friendly expedition report, not public surveillance analytics. */
import { Link } from "wouter";
import { BarChart3, BookOpen, Crosshair, Flame, ShieldCheck, Sparkles, Swords } from "lucide-react";
import { MAGIC_MEDIA, STATIONS } from "@/game/gameData";
import { useGame } from "@/contexts/GameContext";

export default function StatsPage() {
  const { profile, stationProgress, siteVisitCount, lastSiteVisitAt, mostUsedMagicElement, magicBookWatchedCount, hasMagicBookAchievement } = useGame();
  if (!profile) return <section className="stats-blank-dossier"><header><p className="section-kicker">HỒ SƠ DÃ NGOẠI · CHỜ KÝ TÊN</p><h1 className="font-display text-4xl font-black">Báo cáo bằng chứng chưa niêm phong</h1><p>Nhật ký của em đang chờ chủ nhân. Khi tạo hồ sơ, mỗi câu đúng sẽ để lại một dấu mực trên tuyến đường này.</p></header><div className="stats-blank-route" aria-label="Tuyến đường đang chờ mở"><span className="is-active">01<br/><small>Ký tên</small></span><i /><span>02<br/><small>Thu thập</small></span><i /><span>03<br/><small>Niêm phong</small></span><i /><span>04<br/><small>Đấu Boss</small></span></div><div className="stats-blank-evidence"><article><p className="section-kicker">DẤU VẾT TRÌNH DUYỆT</p><b>Đã mở {siteVisitCount} lượt</b><small>{lastSiteVisitAt ? `Lần gần nhất ${new Date(lastSiteVisitAt).toLocaleString("vi-VN")}` : "Chưa có lượt ghé thăm được ghi nhận"}</small></article><article className="stats-blank-seal"><ShieldCheck size={27}/><b>6 ô bằng chứng</b><small>đang chờ những lần học đầu tiên</small></article></div><Link href="/start" className="stats-blank-cta">Mở hồ sơ thám hiểm</Link></section>;
  const accuracy = profile.metrics.totalAnswers ? Math.round((profile.metrics.correctAnswers / profile.metrics.totalAnswers) * 100) : 0;
  const mastered = profile.completedStationIds.length;
  const readyStations = STATIONS.filter((station) => station.status === "ready");
  const cards = [
    { label: "Đáp án đã làm", value: profile.metrics.totalAnswers, icon: BookOpen, tone: "bg-[#fff0b6]" },
    { label: "Độ chính xác", value: `${accuracy}%`, icon: Crosshair, tone: "bg-[#e7f2e5]" },
    { label: "Chuỗi học", value: `${profile.streak} ngày`, icon: Flame, tone: "bg-[#ffe4dc]" },
    { label: "Boss thắng", value: profile.metrics.bossWins, icon: Swords, tone: "bg-[#f0e7f6]" },
    { label: "Lượt mở local", value: siteVisitCount, icon: BarChart3, tone: "bg-[#eaf0f7]" },
    { label: "Phép dùng nhiều nhất", value: mostUsedMagicElement ? MAGIC_MEDIA[mostUsedMagicElement].shortLabel : "Chưa có", icon: Sparkles, tone: "bg-[#fff0b6]" },
  ];
  return <section><div className="mb-6"><p className="section-kicker">Bằng chứng hành trình · local only</p><h1 className="font-display text-4xl font-black">Thống kê của {profile.name}</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-[#58708b]">Số liệu chỉ lưu trong trình duyệt đang dùng. Đây là nhật ký học tập, không phải thống kê truy cập công khai của website.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(({ label, value, icon: Icon, tone }) => <article key={label} className={`evidence-card border-2 border-[#172a48] p-4 shadow-[3px_3px_0_#172a48] ${tone}`}><Icon size={18} /><p className="mt-5 font-display text-4xl font-black">{value}</p><p className="mt-1 text-sm font-bold text-[#476275]">{label}</p></article>)}</div><div className="magic-stats-evidence"><Sparkles size={18} /><div><p className="section-kicker">SỔ PHÉP</p><b>{hasMagicBookAchievement ? "Đã nhận huy hiệu Nhà Lưu Trữ Sáu Ấn" : `Đã xem ${magicBookWatchedCount}/6 hoạt ảnh nguyên tố`}</b></div></div><div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_300px]"><article className="paper-stack border-2 border-[#172a48] bg-[#fffdf6] p-5 shadow-[5px_5px_0_#172a48]"><div className="flex items-center gap-2"><BarChart3 size={18} /><h2 className="font-display text-3xl font-black">Dấu vết trạm đã mở</h2></div><div className="mt-5 space-y-4">{readyStations.map((station) => { const item = stationProgress(station.id); const width = Math.min(100, Math.round((item.correct / item.target) * 100)); return <div key={station.id}><div className="flex justify-between gap-3 text-sm font-bold"><span>{station.code} · {station.title}</span><span>{item.correct}/{item.target} đúng</span></div><div className="mt-2 h-3 overflow-hidden border border-[#172a48] bg-[#f5efdf]"><div style={{ width: `${width}%` }} className={`h-full ${station.accent}`} /></div><p className="mt-1 text-xs text-[#58708b]">{item.answered} lượt đã chốt · độ chính xác {item.accuracy}%</p></div>; })}</div></article><aside className="space-y-5"><article className="border-2 border-[#172a48] bg-[#172a48] p-5 text-white shadow-[4px_4px_0_#f6b73c]"><ShieldCheck className="text-[#f6b73c]" /><h2 className="mt-4 font-display text-3xl font-black">{mastered}/20 dấu niêm phong</h2><p className="mt-2 text-sm leading-relaxed text-[#d5dfed]">Một guardian chỉ gia nhập sau 10 câu đúng riêng biệt của trạm đã kiểm chứng.</p></article><article className="evidence-card border-2 border-[#172a48] bg-[#fff8da] p-4"><p className="section-kicker">Lần hoạt động gần nhất</p><p className="mt-2 text-sm font-bold">{profile.metrics.lastActiveAt ? new Date(profile.metrics.lastActiveAt).toLocaleString("vi-VN") : "Chưa có lượt học nào"}</p></article></aside></div></section>;
}
