// Field Journal Quest: weekly study commitments are arranged as a stitched route across the journal.
import { BellRing, CalendarCheck2, CircleAlert, Compass, Gem, MapPinned, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { useGame } from "@/contexts/GameContext";

const DAYS = ["CN", "T2", "T3", "T4", "T5", "T6", "T7"];

function CalendarEmptyArtifact() {
  return <section className="stats-blank-dossier relative overflow-hidden">
    <div className="absolute right-5 top-2 rotate-[14deg] font-display text-7xl font-black text-[#172a48]/5">7D</div>
    <header className="relative grid gap-5 lg:grid-cols-[1fr_245px]"><div><p className="section-kicker">LỊCH TUẦN · CHỜ KÝ TÊN</p><h1 className="font-display text-4xl font-black">Lịch học cần một chủ nhân.</h1><p className="mt-3 max-w-xl">Ký tên vào nhật ký để khoanh ngày học, giữ đường chỉ chuỗi không bị đứt và nhận nhắc trong lúc Math4Fun đang mở.</p><div className="mt-5 inline-flex items-center gap-2 border-2 border-dashed border-[#172a48] bg-[#fff8da] px-3 py-2 text-xs font-bold"><MapPinned size={15} className="text-[#d99818]"/> Một dấu giải đúng là một dấu chân hôm nay.</div></div><aside className="rotate-[-2deg] border-2 border-[#172a48] bg-[#e8f0e4] p-4 shadow-[3px_3px_0_#172a48]"><p className="field-tag">SPECIMEN · STREAK</p><div className="mt-3 grid h-28 place-items-center rounded-full border-2 border-dashed border-[#172a48] bg-[#fffdf6]"><Gem size={36}/></div><p className="mt-3 font-mono text-[10px] font-bold tracking-[.13em]">HẠT GIỐNG 07 NGÀY · SEALED</p><p className="mt-2 text-xs text-[#476275]">Bảy dấu chân liên tiếp sẽ mở huy hiệu đầu tiên.</p></aside></header>
    <div className="stats-blank-route relative mt-7"><span className="is-active">01<small>Ký nhật ký</small></span><i/><span>02<small>Khoanh ngày học</small></span><i/><span>03<small>Ghi dấu hôm nay</small></span></div>
    <div className="relative mt-6 grid gap-3 border-y-2 border-dashed border-[#c9b88c] bg-[#eef1fb] p-4 md:grid-cols-3"><div><p className="field-tag">MỐC 01</p><b className="mt-1 block font-display text-lg">Chọn tuyến tuần</b><p className="text-xs text-[#476275]">Đánh dấu ngày em muốn học.</p></div><div><p className="field-tag">MỐC 02</p><b className="mt-1 block font-display text-lg">Ghi bằng chứng</b><p className="text-xs text-[#476275]">Hoàn thành một câu trong ngày.</p></div><div><p className="field-tag">MỐC 03</p><b className="mt-1 block font-display text-lg">Mở ấn chuỗi</b><p className="text-xs text-[#476275]">Chạm 7 rồi 14 ngày liên tiếp.</p></div></div>
    <Link href="/start" className="stats-blank-cta">Ký tên để vẽ tuyến tuần <Compass className="ml-1 inline" size={15}/></Link>
  </section>;
}

export default function StudyCalendarPage() {
  const { profile, studyDays, setStudyDays, studyReminder, requestStudyNotifications } = useGame();
  if (!profile) return <CalendarEmptyArtifact/>;
  const toggleDay = (day: number) => setStudyDays(studyDays.includes(day) ? studyDays.filter((entry) => entry !== day) : [...studyDays, day]);
  const reminderTone = studyReminder?.state === "today" ? "bg-[#fff0b6]" : studyReminder?.state === "tomorrow" ? "bg-[#e8f0e4]" : "bg-[#eef1fb]";
  return <section><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-kicker">LỊCH HỌC · ROUTE REMINDER</p><h1 className="font-display text-4xl font-black">Lịch tuần của {profile.name}</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-[#58708b]">Khoanh các ngày em muốn học. Khi Math4Fun đang mở, lịch sẽ nhắc trước để bảo vệ chuỗi học.</p></div><div className="border-2 border-[#172a48] bg-[#fff8da] p-3 text-center shadow-[3px_3px_0_#172a48]"><p className="font-mono text-[9px] font-bold tracking-[.13em] text-[#58708b]">CHUỖI HIỆN TẠI</p><p className="font-display text-4xl font-black">{profile.streak}<span className="ml-1 text-sm">ngày</span></p></div></header>
    <section className={`mt-6 border-2 border-[#172a48] p-5 shadow-[5px_5px_0_#172a48] ${reminderTone}`}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="section-kicker">NHẮC TUYẾN HÀNH TRÌNH</p><h2 className="font-display text-3xl font-black">{studyReminder?.state === "today" ? "Đừng để đường chỉ khâu bị ngắt." : "Tuyến kế tiếp đã được đánh dấu."}</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-[#476275]"><CircleAlert className="mr-1 inline text-[#d99818]" size={15}/>{studyReminder?.label}</p></div><button onClick={async () => { const result = await requestStudyNotifications(); window.alert(result.message); }} className="border-2 border-[#172a48] bg-white px-4 py-3 text-sm font-black shadow-[2px_2px_0_#172a48]"><BellRing className="mr-1 inline" size={16}/>Bật nhắc trong game</button></div></section>
    <section className="mt-6 border-2 border-[#172a48] bg-[#fffdf6] p-5 shadow-[5px_5px_0_#172a48]"><div className="flex items-center gap-2"><CalendarCheck2 size={20}/><div><p className="section-kicker">BẢN ĐỒ BẢY NGÀY</p><h2 className="font-display text-3xl font-black">Khoanh ngày sẽ học</h2></div></div><div className="mt-6 grid grid-cols-7 gap-2">{DAYS.map((label, day) => { const active = studyDays.includes(day); const today = new Date().getDay() === day; return <button key={label} onClick={() => toggleDay(day)} aria-pressed={active} className={`min-h-28 border-2 border-[#172a48] p-2 text-left shadow-[2px_2px_0_#172a48] transition ${active ? "bg-[#172a48] text-white" : "bg-[#fff8da] hover:bg-[#fff0b6]"}`}><span className="block font-mono text-[10px] font-bold tracking-[.12em]">{today ? "HÔM NAY" : "NGÀY"}</span><b className="mt-2 block font-display text-3xl">{label}</b><span className={`mt-3 block text-[10px] font-bold ${active ? "text-[#f6b73c]" : "text-[#58708b]"}`}>{active ? "ĐÃ CHỌN" : "ĐỂ TRỐNG"}</span></button>; })}</div><p className="mt-5 border-t-2 border-dashed border-[#d7d0bf] pt-4 text-sm text-[#476275]"><ShieldCheck className="mr-1 inline text-[#3e9b7a]" size={15}/> Lịch được lưu trong hồ sơ local. Nếu chưa học hôm nay, hãy làm một câu hỏi trước 24:00 để đánh dấu ngày học.</p></section>
    <section className="mt-6 border-2 border-dashed border-[#172a48] bg-[#eef1fb] p-5"><p className="section-kicker">QUY TẮC NHẮC CHUỖI</p><div className="mt-3 grid gap-3 md:grid-cols-3"><div><b className="font-display text-xl">1. Chọn tuyến</b><p className="mt-1 text-sm text-[#476275]">Đánh dấu các ngày học thực tế.</p></div><div><b className="font-display text-xl">2. Ghi một bằng chứng</b><p className="mt-1 text-sm text-[#476275]">Một câu trả lời được ghi trong ngày là đủ duy trì nhịp.</p></div><div><b className="font-display text-xl">3. Nhận huy hiệu</b><p className="mt-1 text-sm text-[#476275]">Chuỗi 7 và 14 ngày mở huy hiệu đặc biệt trong dossier.</p></div></div></section></section>;
}
