/** Field Journal Quest shell — paper navigation and a stitched route keep all game pages inside one expedition. */
import { Link, useLocation } from "wouter";
import { BarChart3, BookOpen, Compass, Flame, Gem, Home, LockKeyhole, Map, ShieldCheck, Swords, UserRound, Volume2, VolumeX } from "lucide-react";
import { LOGO_IMAGE } from "@/game/gameData";
import { useGame } from "@/contexts/GameContext";

const navItems = [{ href: "/", label: "Trang chủ", icon: Home }, { href: "/map", label: "Bản đồ học", icon: Map }, { href: "/collection", label: "Bộ sưu tập", icon: Gem }, { href: "/boss", label: "Đấu Boss", icon: Swords }, { href: "/stats", label: "Thống kê", icon: BarChart3 }];
function isActivePath(path: string, href: string) { return href === "/" ? path === "/" : path === href || path.startsWith(`${href}/`); }
function routeLabel(path: string) { if (path === "/start") return "Phiếu khởi đầu của nhà thám hiểm"; if (path.startsWith("/station/")) return "Đang ghi bằng chứng tại một trạm"; if (path === "/collection") return "Dấu niêm phong của đội guardian"; if (path === "/boss") return "Tuyến đường dẫn về đấu trường"; if (path === "/stats") return "Báo cáo local của hành trình"; if (path === "/map") return "Đường chỉ khâu của hành trình"; return "Trang mở đầu của chuyến thám hiểm"; }

export default function GameLayout({ children }: { children: React.ReactNode }) {
  const [location] = useLocation(); const { profile, level, levelProgress, audioEnabled, setAudioEnabled, isBossUnlocked } = useGame(); const progressPercent = Math.round((levelProgress / 250) * 100); const soloStart = location === "/start";
  const emptyArtifact = location === "/collection" ? ["Mẫu guardian niêm phong", "Chọn sổ để ghi tên specimen đầu tiên.", "SEAL 01"] : location === "/boss" ? ["Dossier đấu trường", "Atlas chỉ mở khi người học để lại bằng chứng.", "ARENA LOCK"] : location === "/stats" ? ["Báo cáo chờ ghi", "Các con số sẽ hiện thành dấu vết của riêng em.", "LOG PENDING"] : location.startsWith("/station/") ? ["Phiếu nhiệm vụ trống", "Tuyến này đang chờ nhà thám hiểm ký tên.", "STATION LOCK"] : ["Bản đồ chưa ký tên", "Đường chỉ khâu sẽ sáng theo lựa chọn của em.", "ROUTE DORMANT"];
  return <div className="min-h-screen overflow-x-hidden bg-[#f5efdf] text-[#172a48]"><div className="paper-noise pointer-events-none fixed inset-0 z-0" /><header className="relative z-30 border-b-2 border-[#172a48] bg-[#fffdf6]/95 backdrop-blur"><div className="mx-auto flex max-w-[1536px] items-center justify-between gap-3 px-4 py-3 sm:px-6 lg:px-8"><Link href="/" className="flex items-center gap-2.5" aria-label="Math4Fun trang chủ"><img src={LOGO_IMAGE} alt="Biểu tượng la bàn Math4Fun" className="h-11 w-11 object-contain" /><span className="leading-none"><span className="block font-display text-xl font-black tracking-tight">Math4Fun</span><span className="block font-mono text-[9px] font-bold uppercase tracking-[0.18em] text-[#58708b]">field journal</span></span></Link><div className="flex items-center gap-2">{profile && <span className="hidden items-center gap-2 rounded-full border-2 border-[#172a48] bg-[#172a48] px-3 py-1.5 text-sm font-bold text-white shadow-[2px_2px_0_#f6b73c] sm:flex"><UserRound size={14} className="text-[#f6b73c]" /> {profile.name}</span>}<button onClick={() => setAudioEnabled(!audioEnabled)} className="grid h-9 w-9 place-items-center border-2 border-[#172a48] bg-[#fff8da] shadow-[2px_2px_0_#172a48]" aria-label={audioEnabled ? "Tắt âm thanh" : "Bật âm thanh"}>{audioEnabled ? <Volume2 size={17} /> : <VolumeX size={17} />}</button>{!profile && !soloStart && <Link href="/start" className="border-2 border-[#172a48] bg-[#f6b73c] px-3 py-2 text-sm font-bold shadow-[2px_2px_0_#172a48]">Tạo hồ sơ</Link>}</div></div></header>
    <div className={`relative z-10 mx-auto max-w-[1536px] px-4 py-6 sm:px-6 lg:px-8 ${soloStart ? "" : "lg:grid lg:grid-cols-[220px_minmax(0,1fr)] lg:gap-6"}`}>{!soloStart && <aside className="order-2 mb-6 lg:order-1 lg:mb-0"><div className="sticky top-5 rounded-[1.25rem] border-2 border-[#172a48] bg-[#fffdf6] p-3 shadow-[5px_5px_0_#172a48]"><p className="px-2 pb-3 font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-[#58708b]">Nhật ký hành trình</p><nav className="space-y-1" aria-label="Điều hướng chính">{navItems.map(({ href, label, icon: Icon }) => { const active = isActivePath(location, href); return <Link key={href} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold transition ${active ? "bg-[#172a48] text-white" : "hover:bg-[#fff0b6]"}`}><Icon size={17} className={active ? "text-[#f6b73c]" : "text-[#58708b]"} />{label}</Link>; })}</nav><div className="my-4 border-t-2 border-dashed border-[#d7d0bf]" />{profile ? <><div className="rounded-xl bg-[#e7f2e5] p-3"><div className="flex items-center justify-between text-xs font-bold"><span>Level {level}</span><span>{levelProgress}/250 XP</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white"><div style={{ width: `${progressPercent}%` }} className="h-full rounded-full bg-[#3e9b7a] transition-[width] duration-300" /></div><p className="mt-2 text-xs leading-relaxed text-[#476275]"><Flame className="mr-1 inline text-[#ee6b4e]" size={13} /> Chuỗi học {profile.streak} ngày</p></div><div className="mt-4 border-2 border-dashed border-[#172a48] bg-[#fff8da] p-3 text-xs"><p className="font-mono text-[10px] font-bold tracking-[0.14em]">ĐỘI BATTLE</p><p className="mt-1 font-bold">{profile.teamGuardianIds.length}/3 guardian được chọn</p></div></> : <Link href="/start" className="block overflow-hidden border-2 border-dashed border-[#172a48] bg-[#fff8da] p-3 hover:bg-[#fff0b6]"><span className="font-mono text-[9px] font-bold tracking-[0.14em] text-[#58708b]">{emptyArtifact[2]}</span><span className="mt-2 grid h-16 place-items-center border-y-2 border-dashed border-[#172a48] bg-[#fffdf6]"><span className="relative grid h-10 w-10 place-items-center rounded-full border-2 border-[#172a48] bg-[#d7d0bf] after:absolute after:-right-8 after:top-1/2 after:w-8 after:border-t-2 after:border-dashed after:border-[#172a48]"><LockKeyhole size={16} /></span></span><b className="mt-3 block font-display text-xl">{emptyArtifact[0]}</b><span className="mt-1 block text-xs leading-relaxed text-[#58708b]">{emptyArtifact[1]}</span><span className="mt-3 block text-sm font-bold">Ký tên mở sổ <Compass className="ml-1 inline" size={14} /></span></Link>}<div className="mt-4 text-xs leading-relaxed text-[#58708b]"><ShieldCheck className="mr-1 inline text-[#3e9b7a]" size={13} /> Tiến độ chỉ lưu ở trình duyệt này.</div></div></aside>}
      <main className="min-w-0 lg:order-2"><div className="journey-strip mb-5"><span className="journey-strip-label"><Compass size={13} /> {routeLabel(location)}</span><span className="journey-thread" aria-hidden="true"><i /><i /><i className={location === "/map" ? "is-current" : ""} /><i /><i /></span><span className="journey-strip-proof">{profile ? `LV.${level} · ${profile.correctQuestionIds.length} bằng chứng` : "CHƯA MỞ SỔ"}</span></div>{children}</main></div>
    {!soloStart && <nav className="sticky bottom-0 z-30 grid grid-cols-5 border-t-2 border-[#172a48] bg-[#fffdf6] px-2 py-2 lg:hidden">{navItems.map(({ href, label, icon: Icon }) => { const active = isActivePath(location, href); return <Link key={href} href={href} className={`grid place-items-center gap-1 rounded-lg py-1.5 text-[10px] font-bold ${active ? "bg-[#172a48] text-white" : "text-[#58708b]"}`}><Icon size={16} className={active ? "text-[#f6b73c]" : ""} />{label}</Link>; })}</nav>}<footer className="relative z-10 border-t-2 border-dashed border-[#d7d0bf] px-4 py-5 text-center text-xs text-[#58708b]"><BookOpen className="mr-1 inline-block" size={13} /> Câu hỏi hiển thị có nguồn Archimede Toán 4 Tập 1–2 đã đối chiếu. <ShieldCheck className="ml-1 inline-block text-[#3e9b7a]" size={13} /></footer>{isBossUnlocked && <div className="pointer-events-none fixed bottom-24 right-4 z-20 hidden border-2 border-[#172a48] bg-[#f6b73c] px-3 py-2 text-xs font-black shadow-[3px_3px_0_#172a48] lg:block"><Compass className="mr-1 inline-block" size={14} /> Boss Atlas đã mở</div>}</div>;
}
